/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import javax.swing.JOptionPane;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSPanelsSlider;
import Clases.Cliente;
import Clases.Proveedor;
import Clases.compra;
import Clases.producto;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSComboMetro;
/**
 *
 * @author hectortllo
 */
public class busquedas extends javax.swing.JFrame {

    /**
     * Creates new form Insertar
     */
    int x, y;
    public busquedas() {
        cliente = new Cliente();
        proveedor = new Proveedor();
        producto = new ArrayList<>();
        compra = new compra();
        initComponents();
        cmbBusquedaCliente.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbBusquedaCliente.getModel()));
        cmbDireccionProveedor.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbDireccionProveedor.getModel()));
        cmbProveedorProducto.setModel(proveedor.getProveedor((DefaultComboBoxModel) cmbProveedorProducto.getModel()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisenio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMover = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        lblMenuPrincipal = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pnlBusquedas = new keeptoo.KGradientPanel();
        lblCliente = new javax.swing.JLabel();
        btnBusquedaCliente = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        lblProveedor = new javax.swing.JLabel();
        lblViajeTapachula = new javax.swing.JLabel();
        pnlBusquedaCliente = new keeptoo.KGradientPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombreBusquedaCliente = new javax.swing.JLabel();
        lblDireccionBusquedaCliente = new javax.swing.JLabel();
        cmbBusquedaCliente = new rojerusan.RSComboMetro();
        txtNombreBusquedaCliente = new javax.swing.JTextField();
        btnRegresarBusquedaCliente = new javax.swing.JButton();
        pnlBuscarProveedor = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreProveedor = new javax.swing.JLabel();
        lblApellidoProveedor = new javax.swing.JLabel();
        lblTelefonoProveedor = new javax.swing.JLabel();
        lblDireccionProveedor = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        txtApellidoProveedor = new javax.swing.JTextField();
        cmbDireccionProveedor = new rojerusan.RSComboMetro();
        lblDescripcionProveedor = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDescripcionProveedor = new javax.swing.JTextArea();
        lblDeudaProveedor = new javax.swing.JLabel();
        txtDuedaProveedor = new javax.swing.JTextField();
        btnGuardarProveedor = new javax.swing.JButton();
        btnCancelarProveedor = new javax.swing.JButton();
        btnRegresarProveedor = new javax.swing.JButton();
        pnlBuscarTapachula = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblPresentacionProducto = new javax.swing.JLabel();
        lblDescripcionProducto = new javax.swing.JLabel();
        lblCostoProducto = new javax.swing.JLabel();
        lblPrecioProducto = new javax.swing.JLabel();
        lblCantidadProducto = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        txtPresentacionProducto = new javax.swing.JTextField();
        txtDescripcionProducto = new javax.swing.JTextField();
        txtCostoProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        lblTipoCompra = new javax.swing.JLabel();
        cmbProveedorProducto = new rojerusan.RSComboMetro();
        jScrollPane4 = new javax.swing.JScrollPane();
        rsTablaProducto = new rojerusan.RSTableMetro();
        btnFinalizarCompra = new javax.swing.JButton();
        btnRegresarProducto = new javax.swing.JButton();
        btnLimpiarProducto = new javax.swing.JButton();
        btnCancelarCompraProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        btnAñadirProducto = new javax.swing.JButton();
        lblTotalPagar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        txtMontoProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVueltoProducto = new javax.swing.JTextField();
        lblProveedorProducto = new javax.swing.JLabel();
        cmbTipoCompraProducto = new rojerusan.RSComboMetro();

        lblDisenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/lineas.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 30));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblMoverMouseDragged(evt);
            }
        });
        lblMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMoverMousePressed(evt);
            }
        });
        jPanel1.add(lblMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 30));

        pnlOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-página-principal-96.png"))); // NOI18N
        lblMenuPrincipal.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver al menú principal</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuPrincipalMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-eliminar-80.png"))); // NOI18N
        lblCerrar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cerrar aplicación</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 90, 80));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-chevron-abajo-en-círculo-95.png"))); // NOI18N
        lblMinimizar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Minimizar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 100, 100));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        pnlOpciones.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 110));

        jPanel1.add(pnlOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 110));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        pnlBusquedas.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBusquedas.setkGradientFocus(1000);
        pnlBusquedas.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBusquedas.setName("pnlBusquedas"); // NOI18N
        pnlBusquedas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(204, 204, 204));
        lblCliente.setText("CLIENTE");
        pnlBusquedas.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 190, 60));

        btnBusquedaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-usuario-masculino-240.png"))); // NOI18N
        btnBusquedaCliente.setContentAreaFilled(false);
        btnBusquedaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-proveedor-240.png"))); // NOI18N
        btnProveedor.setContentAreaFilled(false);
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        btnProducto.setForeground(new java.awt.Color(204, 204, 204));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-producto-240.png"))); // NOI18N
        btnProducto.setContentAreaFilled(false);
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));

        lblProveedor.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(204, 204, 204));
        lblProveedor.setText("PROVEEDOR");
        pnlBusquedas.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 260, 40));

        lblViajeTapachula.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblViajeTapachula.setForeground(new java.awt.Color(204, 204, 204));
        lblViajeTapachula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViajeTapachula.setText("<html>VIAJES<br>TAPACHULA</html>");
        lblViajeTapachula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBusquedas.add(lblViajeTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 250, 160));

        rSPanelsSlider1.add(pnlBusquedas, "card2");

        pnlBusquedaCliente.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBusquedaCliente.setkGradientFocus(1000);
        pnlBusquedaCliente.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBusquedaCliente.setName("pnlBusquedaCliente"); // NOI18N
        pnlBusquedaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 255, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("BÚSQUEDA POR CLIENTE");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlBusquedaCliente.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1170, 60));

        lblNombreBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblNombreBusquedaCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblNombreBusquedaCliente.setText("Nombre: ");
        pnlBusquedaCliente.add(lblNombreBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblDireccionBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblDireccionBusquedaCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblDireccionBusquedaCliente.setText("Dirección:");
        pnlBusquedaCliente.add(lblDireccionBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        cmbBusquedaCliente.setForeground(new java.awt.Color(153, 102, 255));
        cmbBusquedaCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja una opción", "Agregar" }));
        cmbBusquedaCliente.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbBusquedaCliente.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbBusquedaCliente.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbBusquedaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBusquedaClienteMouseClicked(evt);
            }
        });
        cmbBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedaCliente.add(cmbBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 290, 40));

        txtNombreBusquedaCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtNombreBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtNombreBusquedaCliente.setForeground(new java.awt.Color(153, 102, 255));
        pnlBusquedaCliente.add(txtNombreBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 240, 40));

        btnRegresarBusquedaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarBusquedaCliente.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarBusquedaCliente.setContentAreaFilled(false);
        btnRegresarBusquedaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedaCliente.add(btnRegresarBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 80, 80));

        rSPanelsSlider1.add(pnlBusquedaCliente, "card3");

        pnlBuscarProveedor.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBuscarProveedor.setkGradientFocus(1000);
        pnlBuscarProveedor.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBuscarProveedor.setName("pnlBuscarProveedor"); // NOI18N
        pnlBuscarProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INSERTAR PROVEEDOR");
        pnlBuscarProveedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 60));

        lblNombreProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblNombreProveedor.setForeground(new java.awt.Color(204, 255, 155));
        lblNombreProveedor.setText("Nombre:");
        pnlBuscarProveedor.add(lblNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblApellidoProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblApellidoProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblApellidoProveedor.setText("Apellido:");
        pnlBuscarProveedor.add(lblApellidoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        lblTelefonoProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblTelefonoProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblTelefonoProveedor.setText("Teléfono:");
        pnlBuscarProveedor.add(lblTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        lblDireccionProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblDireccionProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblDireccionProveedor.setText("Dirección:");
        pnlBuscarProveedor.add(lblDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        txtTelefonoProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtTelefonoProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtTelefonoProveedor.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarProveedor.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 270, 40));

        txtNombreProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtNombreProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtNombreProveedor.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarProveedor.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 290, 40));

        txtApellidoProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtApellidoProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtApellidoProveedor.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarProveedor.add(txtApellidoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 290, 40));

        cmbDireccionProveedor.setForeground(new java.awt.Color(153, 102, 255));
        cmbDireccionProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja una opción", "Agregar" }));
        cmbDireccionProveedor.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbDireccionProveedor.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbDireccionProveedor.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbDireccionProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbDireccionProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDireccionProveedorMouseClicked(evt);
            }
        });
        cmbDireccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDireccionProveedorActionPerformed(evt);
            }
        });
        pnlBuscarProveedor.add(cmbDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 270, 40));

        lblDescripcionProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblDescripcionProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblDescripcionProveedor.setText("Descripción:");
        pnlBuscarProveedor.add(lblDescripcionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        txtAreaDescripcionProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtAreaDescripcionProveedor.setColumns(20);
        txtAreaDescripcionProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtAreaDescripcionProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtAreaDescripcionProveedor.setRows(5);
        jScrollPane3.setViewportView(txtAreaDescripcionProveedor);

        pnlBuscarProveedor.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 380, 140));

        lblDeudaProveedor.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        lblDeudaProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblDeudaProveedor.setText("Deuda inicial:");
        pnlBuscarProveedor.add(lblDeudaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtDuedaProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtDuedaProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtDuedaProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtDuedaProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuedaProveedorKeyTyped(evt);
            }
        });
        pnlBuscarProveedor.add(txtDuedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 290, 40));

        btnGuardarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/guardar.png"))); // NOI18N
        btnGuardarProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Guardar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnGuardarProveedor.setContentAreaFilled(false);
        btnGuardarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });
        pnlBuscarProveedor.add(btnGuardarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        btnCancelarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cancelar.png"))); // NOI18N
        btnCancelarProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cancelar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnCancelarProveedor.setContentAreaFilled(false);
        btnCancelarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProveedorActionPerformed(evt);
            }
        });
        pnlBuscarProveedor.add(btnCancelarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        btnRegresarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarProveedor.setContentAreaFilled(false);
        btnRegresarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarProveedorActionPerformed(evt);
            }
        });
        pnlBuscarProveedor.add(btnRegresarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        rSPanelsSlider1.add(pnlBuscarProveedor, "card4");

        pnlBuscarTapachula.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBuscarTapachula.setkGradientFocus(1000);
        pnlBuscarTapachula.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBuscarTapachula.setName("pnlBuscarTapachula"); // NOI18N
        pnlBuscarTapachula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INSERTAR PRODUCTO");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBuscarTapachula.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 50));

        lblNombreProducto.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(204, 255, 155));
        lblNombreProducto.setText("Nombre:");
        pnlBuscarTapachula.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblPresentacionProducto.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblPresentacionProducto.setForeground(new java.awt.Color(204, 255, 155));
        lblPresentacionProducto.setText("Presentación:");
        pnlBuscarTapachula.add(lblPresentacionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lblDescripcionProducto.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblDescripcionProducto.setForeground(new java.awt.Color(204, 255, 155));
        lblDescripcionProducto.setText("Descripción:");
        pnlBuscarTapachula.add(lblDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblCostoProducto.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblCostoProducto.setForeground(new java.awt.Color(204, 255, 155));
        lblCostoProducto.setText("Costo:");
        pnlBuscarTapachula.add(lblCostoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblPrecioProducto.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblPrecioProducto.setForeground(new java.awt.Color(204, 255, 155));
        lblPrecioProducto.setText("Precio:");
        pnlBuscarTapachula.add(lblPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblCantidadProducto.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblCantidadProducto.setForeground(new java.awt.Color(204, 255, 155));
        lblCantidadProducto.setText("Cantidad:");
        pnlBuscarTapachula.add(lblCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txtCantidadProducto.setBackground(new java.awt.Color(204, 204, 255));
        txtCantidadProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtCantidadProducto.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarTapachula.add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 290, 40));

        txtPresentacionProducto.setBackground(new java.awt.Color(204, 204, 255));
        txtPresentacionProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtPresentacionProducto.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarTapachula.add(txtPresentacionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 290, 40));

        txtDescripcionProducto.setBackground(new java.awt.Color(204, 204, 255));
        txtDescripcionProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtDescripcionProducto.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarTapachula.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 290, 40));

        txtCostoProducto.setBackground(new java.awt.Color(204, 204, 255));
        txtCostoProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtCostoProducto.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarTapachula.add(txtCostoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 290, 40));

        txtPrecioProducto.setBackground(new java.awt.Color(204, 204, 255));
        txtPrecioProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarTapachula.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 290, 40));

        txtNombreProducto.setBackground(new java.awt.Color(204, 204, 255));
        txtNombreProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(153, 102, 255));
        pnlBuscarTapachula.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 290, 40));

        lblTipoCompra.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblTipoCompra.setForeground(new java.awt.Color(204, 255, 155));
        lblTipoCompra.setText("Tipo Compra:");
        pnlBuscarTapachula.add(lblTipoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        cmbProveedorProducto.setForeground(new java.awt.Color(153, 102, 255));
        cmbProveedorProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja una opción", "Agregar" }));
        cmbProveedorProducto.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbProveedorProducto.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbProveedorProducto.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbProveedorProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbProveedorProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbProveedorProductoMouseClicked(evt);
            }
        });
        cmbProveedorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedorProductoActionPerformed(evt);
            }
        });
        pnlBuscarTapachula.add(cmbProveedorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 290, 40));

        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rsTablaProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rsTablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Costo", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }
    );
    rsTablaProducto.setAltoHead(40);
    rsTablaProducto.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
    rsTablaProducto.setFuenteFilas(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
    rsTablaProducto.setFuenteFilasSelect(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
    rsTablaProducto.setFuenteHead(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
    rsTablaProducto.setRowHeight(25);
    jScrollPane4.setViewportView(rsTablaProducto);

    pnlBuscarTapachula.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 560, 310));

    btnFinalizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/finalizar_compra.png"))); // NOI18N
    btnFinalizarCompra.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Finalizar compra</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
    btnFinalizarCompra.setContentAreaFilled(false);
    btnFinalizarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnFinalizarCompra.setEnabled(false);
    btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnFinalizarCompraActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(btnFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 470, -1, -1));

    btnRegresarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
    btnRegresarProducto.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
    btnRegresarProducto.setContentAreaFilled(false);
    btnRegresarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRegresarProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRegresarProductoActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(btnRegresarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 90, 80));

    btnLimpiarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/limpiar.png"))); // NOI18N
    btnLimpiarProducto.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Limpiar campos</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
    btnLimpiarProducto.setContentAreaFilled(false);
    btnLimpiarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnLimpiarProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLimpiarProductoActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(btnLimpiarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, -1, -1));

    btnCancelarCompraProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cancelar_compra.png"))); // NOI18N
    btnCancelarCompraProducto.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cancelar compra</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
    btnCancelarCompraProducto.setContentAreaFilled(false);
    btnCancelarCompraProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnCancelarCompraProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarCompraProductoActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(btnCancelarCompraProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

    btnEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/editar.png"))); // NOI18N
    btnEditarProducto.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Editar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
    btnEditarProducto.setContentAreaFilled(false);
    btnEditarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnEditarProducto.setEnabled(false);
    btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEditarProductoActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(btnEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, -1));

    btnCancelarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cancelar.png"))); // NOI18N
    btnCancelarProducto.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cancelar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
    btnCancelarProducto.setContentAreaFilled(false);
    btnCancelarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnCancelarProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarProductoActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(btnCancelarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 455, 100, 90));

    btnAñadirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/añadir.png"))); // NOI18N
    btnAñadirProducto.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Añadir</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
    btnAñadirProducto.setContentAreaFilled(false);
    btnAñadirProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnAñadirProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAñadirProductoActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(btnAñadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 100, 70));

    lblTotalPagar.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    lblTotalPagar.setForeground(new java.awt.Color(204, 255, 115));
    lblTotalPagar.setText("Total a pagar:");
    pnlBuscarTapachula.add(lblTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

    jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(204, 255, 115));
    jLabel1.setText("Monto:");
    pnlBuscarTapachula.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

    txtTotalPagar.setEditable(false);
    txtTotalPagar.setBackground(new java.awt.Color(204, 204, 255));
    txtTotalPagar.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    txtTotalPagar.setForeground(new java.awt.Color(153, 102, 255));
    pnlBuscarTapachula.add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 180, 40));

    txtMontoProducto.setBackground(new java.awt.Color(204, 204, 255));
    txtMontoProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    txtMontoProducto.setForeground(new java.awt.Color(153, 102, 255));
    pnlBuscarTapachula.add(txtMontoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 180, 40));

    jLabel6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(204, 255, 115));
    jLabel6.setText("Vuelto:");
    pnlBuscarTapachula.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, -1, -1));

    txtVueltoProducto.setEditable(false);
    txtVueltoProducto.setBackground(new java.awt.Color(204, 204, 255));
    txtVueltoProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    txtVueltoProducto.setForeground(new java.awt.Color(153, 102, 255));
    pnlBuscarTapachula.add(txtVueltoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, 180, 40));

    lblProveedorProducto.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
    lblProveedorProducto.setForeground(new java.awt.Color(204, 255, 155));
    lblProveedorProducto.setText("Proveedor:");
    pnlBuscarTapachula.add(lblProveedorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

    cmbTipoCompraProducto.setForeground(new java.awt.Color(153, 102, 255));
    cmbTipoCompraProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja una opción", "Contado", "Crédito" }));
    cmbTipoCompraProducto.setColorArrow(new java.awt.Color(255, 204, 204));
    cmbTipoCompraProducto.setColorBorde(new java.awt.Color(153, 153, 255));
    cmbTipoCompraProducto.setColorFondo(new java.awt.Color(204, 204, 255));
    cmbTipoCompraProducto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    cmbTipoCompraProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmbTipoCompraProductoActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(cmbTipoCompraProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 402, 290, 40));

    rSPanelsSlider1.add(pnlBuscarTapachula, "card5");

    jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1170, 550));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "CERRANDO", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lblMoverMouseDragged

    private void lblMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblMoverMousePressed

    private void btnBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaClienteActionPerformed
        if(!this.btnBusquedaCliente.isSelected())
        {
            rSPanelsSlider1.setPanelSlider(10, pnlBusquedaCliente, RSPanelsSlider.DIRECT.RIGHT);
            this.btnBusquedaCliente.setSelected(true);
            this.btnProducto.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnCancelarProveedor.setSelected(false);
            this.btnGuardarProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnCancelarProducto.setSelected(false);
            this.btnEditarProducto.setSelected(false);
            this.btnLimpiarProducto.setSelected(false);
            this.btnCancelarCompraProducto.setSelected(false);
            this.btnAñadirProducto.setSelected(false);
            this.btnFinalizarCompra.setSelected(false);
            this.btnRegresarProducto.setSelected(false);
        }
    }//GEN-LAST:event_btnBusquedaClienteActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        if(!this.btnProveedor.isSelected())
        {
            this.btnProveedor.setSelected(true);
            this.btnBusquedaCliente.setSelected(false);
            this.btnProducto.setSelected(false);
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnCancelarProveedor.setSelected(false);
            this.btnGuardarProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnCancelarProducto.setSelected(false);
            this.btnEditarProducto.setSelected(false);
            this.btnLimpiarProducto.setSelected(false);
            this.btnCancelarCompraProducto.setSelected(false);
            this.btnAñadirProducto.setSelected(false);
            this.btnFinalizarCompra.setSelected(false);
            this.btnRegresarProducto.setSelected(false);
            rSPanelsSlider1.setPanelSlider(10, pnlBuscarProveedor, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        if(!this.btnProducto.isSelected())
        {
            this.btnProducto.setSelected(true);
            this.btnBusquedaCliente.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnCancelarProveedor.setSelected(false);
            this.btnGuardarProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnCancelarProducto.setSelected(false);
            this.btnEditarProducto.setSelected(false);
            this.btnLimpiarProducto.setSelected(false);
            this.btnCancelarCompraProducto.setSelected(false);
            this.btnAñadirProducto.setSelected(false);
            this.btnFinalizarCompra.setSelected(false);
            this.btnRegresarProducto.setSelected(false);
            agregarCamposAComboBox(cmbProveedorProducto, cmbDireccionProveedor, 2);
            rSPanelsSlider1.setPanelSlider(10, pnlBuscarTapachula, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnProductoActionPerformed

    private void lblMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuPrincipalMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "¿Volver al menú principal?", "MENÚ PRINCIPAL", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
        {
            this.dispose();
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
        }
            
    }//GEN-LAST:event_lblMenuPrincipalMouseClicked

    private void btnRegresarBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarBusquedaClienteActionPerformed
        if(!this.btnRegresarBusquedaCliente.isSelected())
        {
            this.btnRegresarBusquedaCliente.setSelected(true);
            this.btnBusquedaCliente.setSelected(false);
            this.btnProducto.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnGuardarProveedor.setSelected(false);
            this.btnCancelarProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnCancelarProducto.setSelected(false);
            this.btnEditarProducto.setSelected(false);
            this.btnLimpiarProducto.setSelected(false);
            this.btnCancelarCompraProducto.setSelected(false);
            this.btnAñadirProducto.setSelected(false);
            this.btnFinalizarCompra.setSelected(false);
            this.btnRegresarProducto.setSelected(false);
            rSPanelsSlider1.setPanelSlider(10, pnlBusquedas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnRegresarBusquedaClienteActionPerformed

    private void limpiarCajasProveedor()
    {
        txtNombreProveedor.setText("");
        txtApellidoProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtDuedaProveedor.setText("");
        txtAreaDescripcionProveedor.setText("");
        cmbDireccionProveedor.setSelectedIndex(0);
    }
    
    /*Debo verificar hacia qué panel debe regresar el programa al terminar de ingresar un proveedor.
        1. Al ingresar un proveedor desde el botón "Ingresar proveedor" debe regresar al menún principal.
        2. Al ingresar un proveedor desde la opción de agregar proveedro que está en el panel producto debe
            regresar al panel Producto
    */
    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed
        
        
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private void btnCancelarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProveedorActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "¿Desea cancelar?", "CANCELAR", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
            limpiarCajasProveedor();
    }//GEN-LAST:event_btnCancelarProveedorActionPerformed

    private void btnRegresarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarProveedorActionPerformed
        if(!this.btnRegresarProveedor.isSelected())
        {
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnBusquedaCliente.setSelected(false);
            this.btnProducto.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnGuardarProveedor.setSelected(false);
            this.btnCancelarProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(true);
            this.btnCancelarProducto.setSelected(false);
            this.btnEditarProducto.setSelected(false);
            this.btnLimpiarProducto.setSelected(false);
            this.btnCancelarCompraProducto.setSelected(false);
            this.btnAñadirProducto.setSelected(false);
            this.btnFinalizarCompra.setSelected(false);
            this.btnRegresarProducto.setSelected(false);
            rSPanelsSlider1.setPanelSlider(10, pnlBusquedas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnRegresarProveedorActionPerformed

    private void cmbBusquedaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBusquedaClienteMouseClicked
    }//GEN-LAST:event_cmbBusquedaClienteMouseClicked

    private void cmbDireccionProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDireccionProveedorMouseClicked
    }//GEN-LAST:event_cmbDireccionProveedorMouseClicked

    private void cmbDireccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDireccionProveedorActionPerformed
        if(cmbDireccionProveedor.getSelectedItem().equals("Agregar"))
        {
            agregarCamposAComboBox(cmbDireccionProveedor, cmbBusquedaCliente, 1);
        }
    }//GEN-LAST:event_cmbDireccionProveedorActionPerformed

    private void Numeros(KeyEvent e) {
        if ((e.getKeyChar() < '0' || e.getKeyChar() > '9')) {                           //Si no es un numero se va a consumir 
            e.consume();
        }
    }
    
    private void agregarCamposAComboBox(RSComboMetro cmbDireccionCliente, RSComboMetro cmbDireccionProveedor, int opcion)
    {
        for (int i = cmbDireccionCliente.getItemCount() - 1; i > 0; i--) {
                cmbDireccionCliente.removeItemAt(i);
        }
        for (int i = cmbDireccionProveedor.getItemCount() - 1; i > 0; i--) {
                cmbDireccionProveedor.removeItemAt(i);
        }
        //cmbDireccion.removeAllItems();
        //cmbDireccion.addItem("Escoja una opción");
        cmbDireccionCliente.addItem("Agregar");
        cmbDireccionProveedor.addItem("Agregar");
        switch(opcion)
        {    
            case 1:
                String direccion = JOptionPane.showInputDialog("Ingrese la nueva dirección: ");
                if(direccion != null)
                {
                    /*Actualizar los cmb del cliente y del proveedor. Entrará en este caso si la dirección
                        ingresada fue desde el cmb de cliente
                    */
                    proveedor.insertarDireccion(direccion);
                    cmbDireccionCliente.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbDireccionCliente.getModel()));
                    cmbDireccionProveedor.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbDireccionProveedor.getModel()));
                }
                break;
                
            case 2:
                cmbDireccionCliente.setModel(proveedor.getProveedor((DefaultComboBoxModel) cmbDireccionCliente.getModel()));
                break;
        }
    }
    private void cmbBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBusquedaClienteActionPerformed
        if(cmbBusquedaCliente.getSelectedItem().equals("Agregar"))
        {
            agregarCamposAComboBox(cmbBusquedaCliente, cmbDireccionProveedor, 1);
        }
    }//GEN-LAST:event_cmbBusquedaClienteActionPerformed

    private void txtDuedaProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuedaProveedorKeyTyped
        Numeros(evt);
    }//GEN-LAST:event_txtDuedaProveedorKeyTyped

    private boolean verificarFinalizarCompra()
    {
        if(txtMontoProducto.getText().length() == 0){
            new rojerusan.RSNotifyAnimated("ERROR", "Campo Monto vacío, favor de llenarlo",
                5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            txtMontoProducto.requestFocus();
            return false;
        } else            
            return true;
    }
    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "¿Finalizar venta?", "FINALIZANDO VENTA", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION){
            if(verificarFinalizarCompra()){
                float monto = Float.parseFloat(txtMontoProducto.getText());
                float total = Float.parseFloat(txtTotalPagar.getText());
                if(monto < total){
                    new rojerusan.RSNotifyAnimated("ERROR", "El monto no puede ser menor a la cantidad a pagar",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
                    txtMontoProducto.requestFocus();
                } else {                    
                    float vuelto = monto - total;
                    txtVueltoProducto.setText(String.valueOf(vuelto));
                    if(compra.insertarCompra(Float.parseFloat(txtTotalPagar.getText()))){
                        producto.forEach((productos) -> {
                            compra.insertarProductos(productos.getNombre(), productos.getCantidad(),
                                    productos.getPrecio(), productos.getCosto(), productos.getDescripcion(),
                                    productos.getPresentacion(), productos.getProveedor_id(), productos.getTipo_compra(), 
                                    productos.getFinalizado());
                        });
                        new rojerusan.RSNotifyAnimated("¡ÉXITO!", "Compra realizada con éxito",
                        5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                        RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                        btnFinalizarCompra.setEnabled(false);
                        bloquear_DesbloquearDatosProducto(false);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void btnRegresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarProductoActionPerformed
        if(!this.btnRegresarProducto.isSelected())
        {
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnBusquedaCliente.setSelected(false);
            this.btnProducto.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnGuardarProveedor.setSelected(false);
            this.btnCancelarProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnCancelarProducto.setSelected(false);
            this.btnEditarProducto.setSelected(false);
            this.btnLimpiarProducto.setSelected(false);
            this.btnCancelarCompraProducto.setSelected(false);
            this.btnAñadirProducto.setSelected(false);
            this.btnFinalizarCompra.setSelected(false);
            this.btnRegresarProducto.setSelected(true);
            rSPanelsSlider1.setPanelSlider(10, pnlBusquedas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnRegresarProductoActionPerformed

    private void btnLimpiarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarProductoActionPerformed
        limpiarTablaProducto();
        bloquear_DesbloquearDatosProducto(true);
    }//GEN-LAST:event_btnLimpiarProductoActionPerformed

    private void btnCancelarCompraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarCompraProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void btnCancelarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProductoActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "CERRANDO", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION){
            limpiarProducto();
            limpiarTablaProducto();
            producto.clear();
        }
    }//GEN-LAST:event_btnCancelarProductoActionPerformed

    private void btnAñadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProductoActionPerformed
        
    }//GEN-LAST:event_btnAñadirProductoActionPerformed

    private void cmbProveedorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedorProductoActionPerformed
        if(cmbProveedorProducto.getSelectedItem().equals("Agregar"))
        {
            cmbDireccionProveedor.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbDireccionProveedor.getModel()));
            rSPanelsSlider1.setPanelSlider(10, pnlBuscarProveedor, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_cmbProveedorProductoActionPerformed

    private void cmbProveedorProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProveedorProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedorProductoMouseClicked

    private void cmbTipoCompraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoCompraProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoCompraProductoActionPerformed

    private void limpiarProducto()
    {
        txtNombreProducto.setText("");
        txtPrecioProducto.setText("");
        txtCostoProducto.setText("");
        txtPresentacionProducto.setText("");
        txtDescripcionProducto.setText("");
        txtCantidadProducto.setText("");
        cmbProveedorProducto.setSelectedIndex(0);
        cmbTipoCompraProducto.setSelectedIndex(0);
    }
    
    private void bloquear_DesbloquearDatosProducto(boolean bloqueo){
        txtNombreProducto.setEnabled(bloqueo);
        txtCantidadProducto.setEnabled(bloqueo);
        txtPrecioProducto.setEnabled(bloqueo);
        txtCostoProducto.setEnabled(bloqueo);
        txtDescripcionProducto.setEnabled(bloqueo);
        txtPresentacionProducto.setEnabled(bloqueo);
        cmbProveedorProducto.setEnabled(bloqueo);
        cmbTipoCompraProducto.setEnabled(bloqueo);        
        txtMontoProducto.setEnabled(bloqueo);
        btnAñadirProducto.setEnabled(bloqueo);
        btnCancelarCompraProducto.setEnabled(bloqueo);
        btnAñadirProducto.setEnabled(bloqueo);
    }
    
    private void limpiarTablaProducto(){
        limpiarProducto();
        DefaultTableModel modelo = (DefaultTableModel) rsTablaProducto.getModel();
        for (int i = 0; i < rsTablaProducto.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        txtTotalPagar.setText("");
        txtMontoProducto.setText("");
        txtVueltoProducto.setText("");
        producto.clear();
    }
    private void agregarProducto()
    {
        String nombre = txtNombreProducto.getText();
        int cantidad = Integer.parseInt(txtCantidadProducto.getText());
        float precio = Float.parseFloat(txtPrecioProducto.getText());
        float costo = Float.parseFloat(txtCostoProducto.getText());
        String descripcion = txtDescripcionProducto.getText();
        String presentacion = txtPresentacionProducto.getText();
        int proveedor_id = cmbProveedorProducto.getSelectedIndex() - 1;
        int tipo_compra = cmbTipoCompraProducto.getSelectedIndex();
        System.out.println("tipo: " + tipo_compra);
        float subtotal = cantidad * costo;
        float total = 0;
        if(txtTotalPagar.getText().length() == 0)
            total = subtotal;
        else
            total = Float.parseFloat(txtTotalPagar.getText()) + subtotal;
        producto.add(new producto());
        producto.get(producto.size()-1).setNombre(nombre);
        producto.get(producto.size()-1).setCantidad(cantidad);
        producto.get(producto.size()-1).setPrecio(precio);
        producto.get(producto.size()-1).setCosto(costo);
        producto.get(producto.size()-1).setDescripcion(descripcion);
        producto.get(producto.size()-1).setPresentacion(presentacion);
        producto.get(producto.size()-1).setProveedor_id(proveedor_id);
        //Si tipo_compra es igual a 1 la compra fue al contado
        if(tipo_compra == 1){
            producto.get(producto.size()-1).setTipo_compra(true);
            producto.get(producto.size()-1).setFinalizado(true);
        }
        else {
            producto.get(producto.size()-1).setTipo_compra(false);
            producto.get(producto.size()-1).setFinalizado(false);
        }
        
        DefaultTableModel modelo = (DefaultTableModel) rsTablaProducto.getModel();
        
        String[] datos = new String[4];
        datos[0] = nombre;
        datos[1] = String.valueOf(cantidad);
        datos[2] = String.valueOf(costo);
        datos[3] = String.valueOf(subtotal);
        modelo.addRow(datos);
        txtTotalPagar.setText(String.valueOf(total));
        limpiarProducto();
        btnFinalizarCompra.setEnabled(true);
        for(int i=0; i<producto.size(); i++)
        {
            System.out.println("Nombre: " + producto.get(i).getNombre());
            System.out.println("Cantidad: " + producto.get(i).getCantidad());
            System.out.println("Precio: " + producto.get(i).getPrecio());
            System.out.println("Costo: " + producto.get(i).getCosto());
            System.out.println("Descripción: " + producto.get(i).getDescripcion());
            System.out.println("Presentación: " + producto.get(i).getPresentacion());
            System.out.println("Proveedor: " + producto.get(i).getProveedor_id());
            System.out.println("Proveedor: " + producto.get(i).getTipo_compra());
            System.out.println("Proveedor: " + producto.get(i).getFinalizado());
        }
    }
    
    
   
       
    private final Cliente cliente;
    private final Proveedor proveedor;
    private ArrayList<producto> producto;
    private final compra compra;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirProducto;
    private javax.swing.JButton btnBusquedaCliente;
    private javax.swing.JButton btnCancelarCompraProducto;
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnCancelarProveedor;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnGuardarProveedor;
    private javax.swing.JButton btnLimpiarProducto;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnRegresarBusquedaCliente;
    private javax.swing.JButton btnRegresarProducto;
    private javax.swing.JButton btnRegresarProveedor;
    private rojerusan.RSComboMetro cmbBusquedaCliente;
    private rojerusan.RSComboMetro cmbDireccionProveedor;
    private rojerusan.RSComboMetro cmbProveedorProducto;
    private rojerusan.RSComboMetro cmbTipoCompraProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblApellidoProveedor;
    private javax.swing.JLabel lblCantidadProducto;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCostoProducto;
    private javax.swing.JLabel lblDescripcionProducto;
    private javax.swing.JLabel lblDescripcionProveedor;
    private javax.swing.JLabel lblDeudaProveedor;
    private javax.swing.JLabel lblDireccionBusquedaCliente;
    private javax.swing.JLabel lblDireccionProveedor;
    private javax.swing.JLabel lblDisenio;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblMover;
    private javax.swing.JLabel lblNombreBusquedaCliente;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNombreProveedor;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblPresentacionProducto;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblProveedorProducto;
    private javax.swing.JLabel lblTelefonoProveedor;
    private javax.swing.JLabel lblTipoCompra;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JLabel lblViajeTapachula;
    private keeptoo.KGradientPanel pnlBuscarProveedor;
    private keeptoo.KGradientPanel pnlBuscarTapachula;
    private keeptoo.KGradientPanel pnlBusquedaCliente;
    private keeptoo.KGradientPanel pnlBusquedas;
    private javax.swing.JPanel pnlOpciones;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSTableMetro rsTablaProducto;
    private javax.swing.JTextField txtApellidoProveedor;
    private javax.swing.JTextArea txtAreaDescripcionProveedor;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCostoProducto;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtDuedaProveedor;
    private javax.swing.JTextField txtMontoProducto;
    private javax.swing.JTextField txtNombreBusquedaCliente;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtPresentacionProducto;
    private javax.swing.JTextField txtTelefonoProveedor;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtVueltoProducto;
    // End of variables declaration//GEN-END:variables
}
