/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import javax.swing.JOptionPane;
import rojerusan.RSPanelsSlider;
import Clases.Cliente;
import Clases.Proveedor;
import Clases.compra;
import Clases.viajes_tapachula;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JTextField;
import keeptoo.KGradientPanel;
import rojerusan.RSNotifyAnimated;

/**
 *
 * @author hectortllo
 */
public class busquedas extends javax.swing.JFrame {

    /**
     * Creates new form Insertar
     */
    int x, y;

    public busquedas() {
        cliente = new Cliente();
        proveedor = new Proveedor();
        compra = new compra();
        tapachula = new viajes_tapachula();
        initComponents();
        setLocationRelativeTo(this);
        lblClienteId.setVisible(false);
        lblProveedorId.setVisible(false);
        lblTapachulaId.setVisible(false);
        cmbBusquedaCliente.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbBusquedaCliente.getModel()));
        cmbBusquedaProveedor.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbBusquedaProveedor.getModel()));
        cmbAnioTapachula.setModel(tapachula.getAnio((DefaultComboBoxModel) cmbAnioTapachula.getModel()));
        cmbDireccionEditarCliente.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbDireccionEditarCliente.getModel()));
        cmbEditarDireccionProveedor.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbEditarDireccionProveedor.getModel()));
        tblBusquedaCliente.setModel(cliente.buscarClientes("", "", tblBusquedaCliente));
        tblBusquedaProveedor.setModel(proveedor.buscarProveedores("", "", tblBusquedaProveedor));
        tblBusquedaTapachula.setModel(tapachula.buscarViajeTapachula((String) cmbAnioTapachula.getSelectedItem(), (String) cmbMesTapachula.getSelectedItem(), tblBusquedaTapachula));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisenio = new javax.swing.JLabel();
        PMEditarCliente = new javax.swing.JPopupMenu();
        MenuEditarCliente = new javax.swing.JMenu();
        ItemEditarCliente = new javax.swing.JMenuItem();
        ItemDetalleCliente = new javax.swing.JMenuItem();
        PMEditarProveedor = new javax.swing.JPopupMenu();
        MenuEditarProveedor = new javax.swing.JMenu();
        ItemEditarProveedor = new javax.swing.JMenuItem();
        ItemDetalleProveedor = new javax.swing.JMenuItem();
        PMEditarTapachula = new javax.swing.JPopupMenu();
        MenuEditarTapachula = new javax.swing.JMenu();
        ItemEditarTapachula = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblMover = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        lblMenuPrincipal = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pnlBusquedas = new keeptoo.KGradientPanel();
        lblCliente = new javax.swing.JLabel();
        btnBusquedaCliente = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnBusquedaTapachula = new javax.swing.JButton();
        lblProveedor = new javax.swing.JLabel();
        lblViajeTapachula = new javax.swing.JLabel();
        lblViajeTapachula1 = new javax.swing.JLabel();
        pnlBusquedaCliente = new keeptoo.KGradientPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombreBusquedaCliente = new javax.swing.JLabel();
        lblDireccionBusquedaCliente = new javax.swing.JLabel();
        cmbBusquedaCliente = new rojerusan.RSComboMetro();
        txtNombreBusquedaCliente = new javax.swing.JTextField();
        btnRegresarBusquedaCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusquedaCliente = new rojerusan.RSTableMetro();
        pnlBuscarProveedor = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreBusquedaProveedor = new javax.swing.JLabel();
        lblDireccionBusquedaProveedor = new javax.swing.JLabel();
        txtNombreBusquedaProveedor = new javax.swing.JTextField();
        cmbBusquedaProveedor = new rojerusan.RSComboMetro();
        btnRegresarProveedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBusquedaProveedor = new rojerusan.RSTableMetro();
        pnlBuscarTapachula = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        lblMesTapachula = new javax.swing.JLabel();
        cmbAnioTapachula = new rojerusan.RSComboMetro();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBusquedaTapachula = new rojerusan.RSTableMetro();
        btnRegresarProducto = new javax.swing.JButton();
        lblAnioTapachula = new javax.swing.JLabel();
        cmbMesTapachula = new rojerusan.RSComboMetro();
        lblTapachulaId = new javax.swing.JLabel();
        pnlEditarCliente = new keeptoo.KGradientPanel();
        lblClienteId = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblNombreEditarCliente = new javax.swing.JLabel();
        lblApellidoEditarCliente = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        cmbDireccionEditarCliente = new rojerusan.RSComboMetro();
        txtApellidoEditarCliente = new javax.swing.JTextField();
        txtTelefonoEditarCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreEditarCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDescripcionEditarCliente = new javax.swing.JTextArea();
        btnGuardarEditarCliente = new javax.swing.JButton();
        btnRegresarEditarCliente = new javax.swing.JButton();
        btnCancelarEditarCliente = new javax.swing.JButton();
        lblDeudaEditarCliente = new javax.swing.JLabel();
        txtDeudaEditarCliente = new javax.swing.JTextField();
        pnlEditarProveedor = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNombreProveedor = new javax.swing.JLabel();
        lblApellidoProveedor = new javax.swing.JLabel();
        lblTelefonoProveedor = new javax.swing.JLabel();
        lblDireccionProveedor = new javax.swing.JLabel();
        txtEditarTelefonoProveedor = new javax.swing.JTextField();
        txtEditarNombreProveedor = new javax.swing.JTextField();
        txtEditarApellidoProveedor = new javax.swing.JTextField();
        cmbEditarDireccionProveedor = new rojerusan.RSComboMetro();
        lblDescripcionProveedor = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEditarAreaDescripcionProveedor = new javax.swing.JTextArea();
        lblDeudaProveedor = new javax.swing.JLabel();
        txtEditarDuedaProveedor = new javax.swing.JTextField();
        btnEditarGuardarProveedor = new javax.swing.JButton();
        btnEditarCancelarProveedor = new javax.swing.JButton();
        btnEditarRegresarProveedor = new javax.swing.JButton();
        lblProveedorId = new javax.swing.JLabel();
        pnlDetalleTapachula = new keeptoo.KGradientPanel();
        lblDetalleViajeTapachula = new javax.swing.JLabel();
        btnRegresarDetalleTapachula = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDetalleViajeTapachula = new rojerusan.RSTableMetro();

        lblDisenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/lineas.png"))); // NOI18N

        MenuEditarCliente.setBackground(new java.awt.Color(204, 204, 255));
        MenuEditarCliente.setText("Opciones");
        MenuEditarCliente.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N

        ItemEditarCliente.setBackground(new java.awt.Color(204, 204, 255));
        ItemEditarCliente.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        ItemEditarCliente.setText("Editar");
        ItemEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarClienteActionPerformed(evt);
            }
        });
        MenuEditarCliente.add(ItemEditarCliente);

        ItemDetalleCliente.setBackground(new java.awt.Color(204, 204, 255));
        ItemDetalleCliente.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        ItemDetalleCliente.setText("Detalle");
        MenuEditarCliente.add(ItemDetalleCliente);

        PMEditarCliente.add(MenuEditarCliente);

        MenuEditarProveedor.setBackground(new java.awt.Color(204, 204, 255));
        MenuEditarProveedor.setText("Opciones");
        MenuEditarProveedor.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N

        ItemEditarProveedor.setBackground(new java.awt.Color(204, 204, 255));
        ItemEditarProveedor.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        ItemEditarProveedor.setText("Editar");
        ItemEditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarProveedorActionPerformed(evt);
            }
        });
        MenuEditarProveedor.add(ItemEditarProveedor);

        ItemDetalleProveedor.setBackground(new java.awt.Color(204, 204, 255));
        ItemDetalleProveedor.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        ItemDetalleProveedor.setText("Detalle");
        MenuEditarProveedor.add(ItemDetalleProveedor);

        PMEditarProveedor.add(MenuEditarProveedor);

        MenuEditarTapachula.setBackground(new java.awt.Color(204, 204, 255));
        MenuEditarTapachula.setText("Opciones");
        MenuEditarTapachula.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N

        ItemEditarTapachula.setBackground(new java.awt.Color(204, 204, 255));
        ItemEditarTapachula.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        ItemEditarTapachula.setText("Detalle");
        ItemEditarTapachula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarTapachulaActionPerformed(evt);
            }
        });
        MenuEditarTapachula.add(ItemEditarTapachula);

        PMEditarTapachula.add(MenuEditarTapachula);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 30));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblMoverMouseDragged(evt);
            }
        });
        lblMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMoverMousePressed(evt);
            }
        });
        jPanel1.add(lblMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 30));

        pnlOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-página-principal-96.png"))); // NOI18N
        lblMenuPrincipal.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver al menú principal</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuPrincipalMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-eliminar-80.png"))); // NOI18N
        lblCerrar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cerrar aplicación</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 90, 80));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-chevron-abajo-en-círculo-95.png"))); // NOI18N
        lblMinimizar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Minimizar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 100, 100));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        pnlOpciones.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 110));

        jPanel1.add(pnlOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 110));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        pnlBusquedas.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBusquedas.setkGradientFocus(1000);
        pnlBusquedas.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBusquedas.setName("pnlBusquedas"); // NOI18N
        pnlBusquedas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(204, 204, 204));
        lblCliente.setText("CLIENTE");
        pnlBusquedas.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 190, 60));

        btnBusquedaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-usuario-masculino-240.png"))); // NOI18N
        btnBusquedaCliente.setContentAreaFilled(false);
        btnBusquedaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-proveedor-240.png"))); // NOI18N
        btnProveedor.setContentAreaFilled(false);
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        btnBusquedaTapachula.setForeground(new java.awt.Color(204, 204, 204));
        btnBusquedaTapachula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/tapachula.png"))); // NOI18N
        btnBusquedaTapachula.setContentAreaFilled(false);
        btnBusquedaTapachula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusquedaTapachula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaTapachulaActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnBusquedaTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, -1, -1));

        lblProveedor.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(204, 204, 204));
        lblProveedor.setText("PROVEEDOR");
        pnlBusquedas.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 260, 40));

        lblViajeTapachula.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblViajeTapachula.setForeground(new java.awt.Color(204, 204, 204));
        lblViajeTapachula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViajeTapachula.setText("VIAJES");
        lblViajeTapachula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBusquedas.add(lblViajeTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 250, 50));

        lblViajeTapachula1.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblViajeTapachula1.setForeground(new java.awt.Color(204, 204, 204));
        lblViajeTapachula1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViajeTapachula1.setText("TAPACHULA");
        lblViajeTapachula1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBusquedas.add(lblViajeTapachula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 250, 50));

        rSPanelsSlider1.add(pnlBusquedas, "card2");

        pnlBusquedaCliente.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBusquedaCliente.setkGradientFocus(1000);
        pnlBusquedaCliente.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBusquedaCliente.setName("pnlBusquedaCliente"); // NOI18N
        pnlBusquedaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 255, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("BÚSQUEDA POR CLIENTE");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlBusquedaCliente.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1170, 60));

        lblNombreBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblNombreBusquedaCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblNombreBusquedaCliente.setText("Nombre: ");
        pnlBusquedaCliente.add(lblNombreBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        lblDireccionBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblDireccionBusquedaCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblDireccionBusquedaCliente.setText("Dirección:");
        pnlBusquedaCliente.add(lblDireccionBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        cmbBusquedaCliente.setForeground(new java.awt.Color(153, 102, 255));
        cmbBusquedaCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ver Todo" }));
        cmbBusquedaCliente.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbBusquedaCliente.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbBusquedaCliente.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbBusquedaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBusquedaClienteMouseClicked(evt);
            }
        });
        cmbBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedaCliente.add(cmbBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 290, 40));

        txtNombreBusquedaCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtNombreBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtNombreBusquedaCliente.setForeground(new java.awt.Color(153, 102, 255));
        txtNombreBusquedaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreBusquedaClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreBusquedaClienteKeyTyped(evt);
            }
        });
        pnlBusquedaCliente.add(txtNombreBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 240, 40));

        btnRegresarBusquedaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarBusquedaCliente.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarBusquedaCliente.setContentAreaFilled(false);
        btnRegresarBusquedaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedaCliente.add(btnRegresarBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 80, 80));

        tblBusquedaCliente = new rojerusan.RSTableMetro() {
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblBusquedaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Apellido", "Teléfono", "Descripción", "Dirección", "Deuda"
            }
        ));
        tblBusquedaCliente.setAltoHead(40);
        tblBusquedaCliente.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        tblBusquedaCliente.setComponentPopupMenu(PMEditarCliente);
        tblBusquedaCliente.setFuenteFilas(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaCliente.setFuenteFilasSelect(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaCliente.setFuenteHead(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        tblBusquedaCliente.setRowHeight(25);
        tblBusquedaCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblBusquedaCliente);
        if (tblBusquedaCliente.getColumnModel().getColumnCount() > 0) {
            tblBusquedaCliente.getColumnModel().getColumn(4).setHeaderValue("Descripción");
            tblBusquedaCliente.getColumnModel().getColumn(5).setHeaderValue("Dirección");
            tblBusquedaCliente.getColumnModel().getColumn(6).setHeaderValue("Deuda");
        }

        pnlBusquedaCliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 1090, 350));

        rSPanelsSlider1.add(pnlBusquedaCliente, "card3");

        pnlBuscarProveedor.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBuscarProveedor.setkGradientFocus(1000);
        pnlBuscarProveedor.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBuscarProveedor.setName("pnlBuscarProveedor"); // NOI18N
        pnlBuscarProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BÚSQUEDA POR PROVEEDOR");
        pnlBuscarProveedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 60));

        lblNombreBusquedaProveedor.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblNombreBusquedaProveedor.setForeground(new java.awt.Color(204, 255, 155));
        lblNombreBusquedaProveedor.setText("Nombre:");
        pnlBuscarProveedor.add(lblNombreBusquedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        lblDireccionBusquedaProveedor.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblDireccionBusquedaProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblDireccionBusquedaProveedor.setText("Dirección:");
        pnlBuscarProveedor.add(lblDireccionBusquedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        txtNombreBusquedaProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtNombreBusquedaProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtNombreBusquedaProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtNombreBusquedaProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreBusquedaProveedorKeyPressed(evt);
            }
        });
        pnlBuscarProveedor.add(txtNombreBusquedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 290, 40));

        cmbBusquedaProveedor.setForeground(new java.awt.Color(153, 102, 255));
        cmbBusquedaProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ver Todo" }));
        cmbBusquedaProveedor.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbBusquedaProveedor.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbBusquedaProveedor.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbBusquedaProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbBusquedaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBusquedaProveedorMouseClicked(evt);
            }
        });
        cmbBusquedaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBusquedaProveedorActionPerformed(evt);
            }
        });
        pnlBuscarProveedor.add(cmbBusquedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 270, 40));

        btnRegresarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarProveedor.setContentAreaFilled(false);
        btnRegresarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarProveedorActionPerformed(evt);
            }
        });
        pnlBuscarProveedor.add(btnRegresarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 110, 80));

        tblBusquedaProveedor = new rojerusan.RSTableMetro() {
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblBusquedaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Apellido", "Teléfono", "Descripción", "Dirección", "Deuda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBusquedaProveedor.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        tblBusquedaProveedor.setComponentPopupMenu(PMEditarProveedor);
        tblBusquedaProveedor.setFuenteFilas(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaProveedor.setFuenteFilasSelect(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaProveedor.setFuenteHead(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        tblBusquedaProveedor.setRowHeight(25);
        tblBusquedaProveedor.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblBusquedaProveedor);

        pnlBuscarProveedor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1100, 390));

        rSPanelsSlider1.add(pnlBuscarProveedor, "card4");

        pnlBuscarTapachula.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBuscarTapachula.setkGradientFocus(1000);
        pnlBuscarTapachula.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBuscarTapachula.setName("pnlBuscarTapachula"); // NOI18N
        pnlBuscarTapachula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BÚSQUEDA VIAJE TAPACHULA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBuscarTapachula.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 50));

        lblMesTapachula.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblMesTapachula.setForeground(new java.awt.Color(204, 255, 155));
        lblMesTapachula.setText("Mes:");
        pnlBuscarTapachula.add(lblMesTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        cmbAnioTapachula.setForeground(new java.awt.Color(153, 102, 255));
        cmbAnioTapachula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos los años" }));
        cmbAnioTapachula.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbAnioTapachula.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbAnioTapachula.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbAnioTapachula.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbAnioTapachula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbAnioTapachulaMouseClicked(evt);
            }
        });
        cmbAnioTapachula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnioTapachulaActionPerformed(evt);
            }
        });
        pnlBuscarTapachula.add(cmbAnioTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 290, 40));

        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblBusquedaTapachula = new rojerusan.RSTableMetro() {
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblBusquedaTapachula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblBusquedaTapachula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Fecha", "Lugares vistiados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBusquedaTapachula.setAltoHead(40);
        tblBusquedaTapachula.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        tblBusquedaTapachula.setComponentPopupMenu(PMEditarTapachula);
        tblBusquedaTapachula.setFuenteFilas(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaTapachula.setFuenteFilasSelect(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaTapachula.setFuenteHead(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        tblBusquedaTapachula.setRowHeight(25);
        tblBusquedaTapachula.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblBusquedaTapachula);

        pnlBuscarTapachula.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 1090, 390));

        btnRegresarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarProducto.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarProducto.setContentAreaFilled(false);
        btnRegresarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarProductoActionPerformed(evt);
            }
        });
        pnlBuscarTapachula.add(btnRegresarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 90, 80));

        lblAnioTapachula.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblAnioTapachula.setForeground(new java.awt.Color(204, 255, 155));
        lblAnioTapachula.setText("Año:");
        pnlBuscarTapachula.add(lblAnioTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        cmbMesTapachula.setForeground(new java.awt.Color(153, 102, 255));
        cmbMesTapachula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos los meses", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbMesTapachula.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbMesTapachula.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbMesTapachula.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbMesTapachula.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbMesTapachula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesTapachulaActionPerformed(evt);
            }
        });
        pnlBuscarTapachula.add(cmbMesTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 290, 40));
        pnlBuscarTapachula.add(lblTapachulaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        rSPanelsSlider1.add(pnlBuscarTapachula, "card5");

        pnlEditarCliente.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlEditarCliente.setkGradientFocus(1000);
        pnlEditarCliente.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlEditarCliente.setName("pnlEditarCliente"); // NOI18N
        pnlEditarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlEditarCliente.add(lblClienteId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 50, 20));

        lblTitulo1.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(204, 255, 153));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("EDITAR CLIENTE");
        lblTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlEditarCliente.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1170, 50));

        lblNombreEditarCliente.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblNombreEditarCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblNombreEditarCliente.setText("Nombre: ");
        pnlEditarCliente.add(lblNombreEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lblApellidoEditarCliente.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblApellidoEditarCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblApellidoEditarCliente.setText("Apellido:");
        pnlEditarCliente.add(lblApellidoEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(204, 255, 153));
        lblDireccion.setText("Dirección:");
        pnlEditarCliente.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        cmbDireccionEditarCliente.setForeground(new java.awt.Color(153, 102, 255));
        cmbDireccionEditarCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja una opción" }));
        cmbDireccionEditarCliente.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbDireccionEditarCliente.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbDireccionEditarCliente.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbDireccionEditarCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbDireccionEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDireccionEditarClienteMouseClicked(evt);
            }
        });
        cmbDireccionEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDireccionEditarClienteActionPerformed(evt);
            }
        });
        pnlEditarCliente.add(cmbDireccionEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 290, 40));

        txtApellidoEditarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtApellidoEditarCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtApellidoEditarCliente.setForeground(new java.awt.Color(153, 102, 255));
        txtApellidoEditarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoEditarClienteKeyTyped(evt);
            }
        });
        pnlEditarCliente.add(txtApellidoEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 290, 40));

        txtTelefonoEditarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtTelefonoEditarCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtTelefonoEditarCliente.setForeground(new java.awt.Color(153, 102, 255));
        txtTelefonoEditarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoEditarClienteKeyTyped(evt);
            }
        });
        pnlEditarCliente.add(txtTelefonoEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 290, 40));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 153));
        jLabel4.setText("Teléfono:");
        pnlEditarCliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        txtNombreEditarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtNombreEditarCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtNombreEditarCliente.setForeground(new java.awt.Color(153, 102, 255));
        txtNombreEditarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEditarClienteKeyTyped(evt);
            }
        });
        pnlEditarCliente.add(txtNombreEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 290, 40));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 153));
        jLabel5.setText("Descripción:");
        pnlEditarCliente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        txtAreaDescripcionEditarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtAreaDescripcionEditarCliente.setColumns(20);
        txtAreaDescripcionEditarCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtAreaDescripcionEditarCliente.setForeground(new java.awt.Color(153, 102, 255));
        txtAreaDescripcionEditarCliente.setRows(5);
        jScrollPane3.setViewportView(txtAreaDescripcionEditarCliente);

        pnlEditarCliente.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 380, 140));

        btnGuardarEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/guardar.png"))); // NOI18N
        btnGuardarEditarCliente.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Guardar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnGuardarEditarCliente.setContentAreaFilled(false);
        btnGuardarEditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEditarClienteActionPerformed(evt);
            }
        });
        pnlEditarCliente.add(btnGuardarEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        btnRegresarEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarEditarCliente.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarEditarCliente.setContentAreaFilled(false);
        btnRegresarEditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarEditarClienteActionPerformed(evt);
            }
        });
        pnlEditarCliente.add(btnRegresarEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        btnCancelarEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cancelar.png"))); // NOI18N
        btnCancelarEditarCliente.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cancelar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnCancelarEditarCliente.setContentAreaFilled(false);
        btnCancelarEditarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditarClienteActionPerformed(evt);
            }
        });
        pnlEditarCliente.add(btnCancelarEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        lblDeudaEditarCliente.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        lblDeudaEditarCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblDeudaEditarCliente.setText("Deuda inicial:");
        pnlEditarCliente.add(lblDeudaEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txtDeudaEditarCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtDeudaEditarCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtDeudaEditarCliente.setForeground(new java.awt.Color(153, 102, 255));
        txtDeudaEditarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeudaEditarClienteKeyTyped(evt);
            }
        });
        pnlEditarCliente.add(txtDeudaEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 290, 40));

        rSPanelsSlider1.add(pnlEditarCliente, "card3");

        pnlEditarProveedor.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlEditarProveedor.setkGradientFocus(1000);
        pnlEditarProveedor.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlEditarProveedor.setName("pnlEditarProveedor"); // NOI18N
        pnlEditarProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("EDITAR PROVEEDOR");
        pnlEditarProveedor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 60));

        lblNombreProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblNombreProveedor.setForeground(new java.awt.Color(204, 255, 155));
        lblNombreProveedor.setText("Nombre:");
        pnlEditarProveedor.add(lblNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblApellidoProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblApellidoProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblApellidoProveedor.setText("Apellido:");
        pnlEditarProveedor.add(lblApellidoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        lblTelefonoProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblTelefonoProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblTelefonoProveedor.setText("Teléfono:");
        pnlEditarProveedor.add(lblTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        lblDireccionProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblDireccionProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblDireccionProveedor.setText("Dirección:");
        pnlEditarProveedor.add(lblDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        txtEditarTelefonoProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtEditarTelefonoProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtEditarTelefonoProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtEditarTelefonoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarTelefonoProveedorKeyTyped(evt);
            }
        });
        pnlEditarProveedor.add(txtEditarTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 270, 40));

        txtEditarNombreProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtEditarNombreProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtEditarNombreProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtEditarNombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarNombreProveedorKeyTyped(evt);
            }
        });
        pnlEditarProveedor.add(txtEditarNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 290, 40));

        txtEditarApellidoProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtEditarApellidoProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtEditarApellidoProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtEditarApellidoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarApellidoProveedorKeyTyped(evt);
            }
        });
        pnlEditarProveedor.add(txtEditarApellidoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 290, 40));

        cmbEditarDireccionProveedor.setForeground(new java.awt.Color(153, 102, 255));
        cmbEditarDireccionProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja una opción" }));
        cmbEditarDireccionProveedor.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbEditarDireccionProveedor.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbEditarDireccionProveedor.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbEditarDireccionProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbEditarDireccionProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbEditarDireccionProveedorMouseClicked(evt);
            }
        });
        cmbEditarDireccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditarDireccionProveedorActionPerformed(evt);
            }
        });
        pnlEditarProveedor.add(cmbEditarDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 270, 40));

        lblDescripcionProveedor.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblDescripcionProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblDescripcionProveedor.setText("Descripción:");
        pnlEditarProveedor.add(lblDescripcionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        txtEditarAreaDescripcionProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtEditarAreaDescripcionProveedor.setColumns(20);
        txtEditarAreaDescripcionProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtEditarAreaDescripcionProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtEditarAreaDescripcionProveedor.setRows(5);
        jScrollPane5.setViewportView(txtEditarAreaDescripcionProveedor);

        pnlEditarProveedor.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 380, 140));

        lblDeudaProveedor.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        lblDeudaProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblDeudaProveedor.setText("Deuda inicial:");
        pnlEditarProveedor.add(lblDeudaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtEditarDuedaProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtEditarDuedaProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtEditarDuedaProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtEditarDuedaProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditarDuedaProveedorKeyTyped(evt);
            }
        });
        pnlEditarProveedor.add(txtEditarDuedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 290, 40));

        btnEditarGuardarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/guardar.png"))); // NOI18N
        btnEditarGuardarProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Guardar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnEditarGuardarProveedor.setContentAreaFilled(false);
        btnEditarGuardarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGuardarProveedorActionPerformed(evt);
            }
        });
        pnlEditarProveedor.add(btnEditarGuardarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        btnEditarCancelarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cancelar.png"))); // NOI18N
        btnEditarCancelarProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cancelar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnEditarCancelarProveedor.setContentAreaFilled(false);
        btnEditarCancelarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCancelarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCancelarProveedorActionPerformed(evt);
            }
        });
        pnlEditarProveedor.add(btnEditarCancelarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        btnEditarRegresarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnEditarRegresarProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnEditarRegresarProveedor.setContentAreaFilled(false);
        btnEditarRegresarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarRegresarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRegresarProveedorActionPerformed(evt);
            }
        });
        pnlEditarProveedor.add(btnEditarRegresarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));
        pnlEditarProveedor.add(lblProveedorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        rSPanelsSlider1.add(pnlEditarProveedor, "card4");

        pnlDetalleTapachula.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlDetalleTapachula.setkGradientFocus(1000);
        pnlDetalleTapachula.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlDetalleTapachula.setName("pnlBusquedaCliente"); // NOI18N
        pnlDetalleTapachula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDetalleViajeTapachula.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        lblDetalleViajeTapachula.setForeground(new java.awt.Color(204, 255, 153));
        lblDetalleViajeTapachula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDetalleViajeTapachula.setText("DETALLE VAIJE TAPACHULA");
        lblDetalleViajeTapachula.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlDetalleTapachula.add(lblDetalleViajeTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1170, 60));

        btnRegresarDetalleTapachula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarDetalleTapachula.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarDetalleTapachula.setContentAreaFilled(false);
        btnRegresarDetalleTapachula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarDetalleTapachula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDetalleTapachulaActionPerformed(evt);
            }
        });
        pnlDetalleTapachula.add(btnRegresarDetalleTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 80, 80));

        tblDetalleViajeTapachula = new rojerusan.RSTableMetro() {
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblDetalleViajeTapachula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Fecha", "Lugar", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalleViajeTapachula.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        tblDetalleViajeTapachula.setFuenteFilas(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        tblDetalleViajeTapachula.setFuenteFilasSelect(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        tblDetalleViajeTapachula.setFuenteHead(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        tblDetalleViajeTapachula.setRowHeight(25);
        tblDetalleViajeTapachula.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tblDetalleViajeTapachula);

        pnlDetalleTapachula.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 1100, 360));

        rSPanelsSlider1.add(pnlDetalleTapachula, "card3");

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1170, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "CERRANDO", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lblMoverMouseDragged

    private void lblMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblMoverMousePressed

    private void btnBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaClienteActionPerformed
        moverPanel(pnlBusquedaCliente, true, false, btnBusquedaCliente, true);
    }//GEN-LAST:event_btnBusquedaClienteActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        moverPanel(pnlBuscarProveedor, true, false, btnProveedor, true);
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnBusquedaTapachulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaTapachulaActionPerformed
        moverPanel(pnlBuscarTapachula, true, false, btnBusquedaTapachula, true);
    }//GEN-LAST:event_btnBusquedaTapachulaActionPerformed

    private void lblMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuPrincipalMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "¿Volver al menú principal?", "MENÚ PRINCIPAL", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            this.dispose();
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
        }

    }//GEN-LAST:event_lblMenuPrincipalMouseClicked

    private void btnRegresarBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarBusquedaClienteActionPerformed
        moverPanel(pnlBusquedas, true, false, btnRegresarBusquedaCliente, true);
    }//GEN-LAST:event_btnRegresarBusquedaClienteActionPerformed


    private void btnRegresarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarProveedorActionPerformed
        moverPanel(pnlBusquedas, true, false, btnRegresarProveedor, true);
    }//GEN-LAST:event_btnRegresarProveedorActionPerformed

    private void cmbBusquedaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBusquedaClienteMouseClicked
    }//GEN-LAST:event_cmbBusquedaClienteMouseClicked

    private void cmbBusquedaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBusquedaProveedorMouseClicked
    }//GEN-LAST:event_cmbBusquedaProveedorMouseClicked

    private void cmbBusquedaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBusquedaProveedorActionPerformed
        BusquedaProveedor();
    }//GEN-LAST:event_cmbBusquedaProveedorActionPerformed

    private void Numeros(KeyEvent e, int limite, JTextField txtField) {
        if(txtField.getText().length() == limite){
            e.consume();
            if ((e.getKeyChar() < '0' || e.getKeyChar() > '9')) {                           //Si no es un numero se va a consumir 
                e.consume();
            }
        }
    }

    private void BusquedaCliente() {
        //Declaro variables a utilizar. Y les asigno valores con if ternarios si dicen ver todo les mando cadena vacía si no lo que este en el combobox.
        String direccion;
        direccion = cmbBusquedaCliente.getSelectedItem().equals("Ver Todo") ? "" : (String) cmbBusquedaCliente.getSelectedItem();
        tblBusquedaCliente.setModel(cliente.buscarClientes(txtNombreBusquedaCliente.getText(), direccion, tblBusquedaCliente));
    }

    private void BusquedaProveedor() {
        //Declaro variables a utilizar. Y les asigno valores con if ternarios si dicen ver todo les mando cadena vacía si no lo que este en el combobox.
        String direccion;
        direccion = cmbBusquedaProveedor.getSelectedItem().equals("Ver Todo") ? "" : (String) cmbBusquedaProveedor.getSelectedItem();
        tblBusquedaProveedor.setModel(proveedor.buscarProveedores(txtNombreBusquedaProveedor.getText(), direccion, tblBusquedaProveedor));
    }

    private void BusquedaTapachula() {
        String anio, mes;
        anio = cmbAnioTapachula.getSelectedItem().equals("Todos los años") ? "Todos los años" : (String) cmbAnioTapachula.getSelectedItem();
        mes = cmbMesTapachula.getSelectedItem().equals("Todos los meses") ? "Todos los meses" : String.valueOf(cmbMesTapachula.getSelectedIndex());
        tblBusquedaTapachula.setModel(tapachula.buscarViajeTapachula(anio, mes, tblBusquedaTapachula));
    }
    private void cmbBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBusquedaClienteActionPerformed
        BusquedaCliente();
    }//GEN-LAST:event_cmbBusquedaClienteActionPerformed

    private void btnRegresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarProductoActionPerformed
        moverPanel(pnlBusquedas, true, false, btnRegresarProducto, true);
    }//GEN-LAST:event_btnRegresarProductoActionPerformed

    private void cmbAnioTapachulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnioTapachulaActionPerformed
        BusquedaTapachula();
    }//GEN-LAST:event_cmbAnioTapachulaActionPerformed

    private void cmbAnioTapachulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbAnioTapachulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAnioTapachulaMouseClicked

    private void cmbMesTapachulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesTapachulaActionPerformed
        BusquedaTapachula();
    }//GEN-LAST:event_cmbMesTapachulaActionPerformed

    private void txtNombreBusquedaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBusquedaClienteKeyPressed
        BusquedaCliente();
    }//GEN-LAST:event_txtNombreBusquedaClienteKeyPressed

    private void txtNombreBusquedaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBusquedaClienteKeyTyped

    }//GEN-LAST:event_txtNombreBusquedaClienteKeyTyped

    private void txtNombreBusquedaProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBusquedaProveedorKeyPressed
        BusquedaProveedor();
    }//GEN-LAST:event_txtNombreBusquedaProveedorKeyPressed

    private void ItemEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarClienteActionPerformed
        int seleccion = tblBusquedaCliente.getSelectedRow();
        String registros[] = new String[7];
        System.out.println(seleccion);
        if (seleccion != -1) {
            int id = Integer.parseInt((String) tblBusquedaCliente.getValueAt(seleccion, 0));
            System.out.println("seleccion: " + seleccion);
            moverPanel(pnlEditarCliente, false, false, null, false);
            lblClienteId.setText(String.valueOf(id));
            registros = cliente.getCliente(id);
            txtNombreEditarCliente.setText(registros[1]);
            txtApellidoEditarCliente.setText(registros[2]);
            txtAreaDescripcionEditarCliente.setText(registros[3]);
            txtTelefonoEditarCliente.setText(registros[4]);
            cmbDireccionEditarCliente.setSelectedItem(registros[5]);
            txtDeudaEditarCliente.setText(registros[6]);
        }
    }//GEN-LAST:event_ItemEditarClienteActionPerformed

    private void Letras(KeyEvent e) {
        char c = e.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            e.consume();
        }
    }

    private void puntoFlotante(KeyEvent e, JTextField txt) {
        if (!Character.isDigit(e.getKeyChar()) && e.getKeyChar() != '.' && e.getKeyChar() != 8) {
            e.consume();
        }
        if (e.getKeyChar() == '.' && txt.getText().contains(".")) {
            e.consume();
        }
    }

    private void txtApellidoEditarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoEditarClienteKeyTyped
        Letras(evt);
    }//GEN-LAST:event_txtApellidoEditarClienteKeyTyped

    private void txtTelefonoEditarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoEditarClienteKeyTyped
        Numeros(evt, 8, txtTelefonoEditarCliente);
    }//GEN-LAST:event_txtTelefonoEditarClienteKeyTyped

    private void txtNombreEditarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEditarClienteKeyTyped
        Letras(evt);
    }//GEN-LAST:event_txtNombreEditarClienteKeyTyped

    private void limpiarCajasCliente() {
        txtNombreEditarCliente.setText("");
        txtApellidoEditarCliente.setText("");
        txtTelefonoEditarCliente.setText("");
        txtAreaDescripcionEditarCliente.setText("");
        cmbDireccionEditarCliente.setSelectedIndex(0);
        txtDeudaEditarCliente.setText("");
    }

    private boolean verificarCliente() {
        if (txtNombreEditarCliente.getText().length() == 0) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Campo Nombre vacío, por favor llénelo",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            txtNombreEditarCliente.requestFocus();
            return false;
        } else if (txtApellidoEditarCliente.getText().length() == 0) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Campo Apellido vacío, por favor llénelo",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            txtApellidoEditarCliente.requestFocus();
            return false;
        } else if (txtTelefonoEditarCliente.getText().length() == 0) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Campo Teléfono vacío, por favor llénelo",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            txtTelefonoEditarCliente.requestFocus();
            return false;
        } else if (cmbDireccionEditarCliente.getSelectedItem().equals("Escoja una opción")) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Escoja un campo correcto en la dirección",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            cmbDireccionEditarCliente.requestFocus();
            return false;
        } else if (txtDeudaEditarCliente.getText().length() == 0) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Campo Deuda Inicial vacío, por favor llénelo",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            txtDeudaEditarCliente.requestFocus();
            return false;
        } else {
            return true;
        }
    }
    private void btnGuardarEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEditarClienteActionPerformed
        if (verificarCliente()) {
            System.out.println(cmbDireccionEditarCliente.getSelectedIndex());
            if (cliente.ActualizarCliente(Integer.parseInt(lblClienteId.getText()), txtNombreEditarCliente.getText(),
                    txtApellidoEditarCliente.getText(), cmbDireccionEditarCliente.getSelectedIndex(),
                    txtAreaDescripcionEditarCliente.getText(), txtTelefonoEditarCliente.getText(),
                    Float.parseFloat(txtDeudaEditarCliente.getText()))) {
                new rojerusan.RSNotifyAnimated("¡ÉXITO!", "Cliente actualizado correctamente",
                        5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                        RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                limpiarCajasCliente();
            }
            tblBusquedaCliente.setModel(cliente.buscarClientes("", "", tblBusquedaCliente));
            moverPanel(pnlBusquedaCliente, true, false, btnGuardarEditarCliente, true);
        }

    }//GEN-LAST:event_btnGuardarEditarClienteActionPerformed

    private void btnRegresarEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarEditarClienteActionPerformed
        moverPanel(pnlBusquedaCliente, true, false, btnRegresarEditarCliente, true);
    }//GEN-LAST:event_btnRegresarEditarClienteActionPerformed

    private void btnCancelarEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditarClienteActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "¿Desea cancelar?", "CANCELAR", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            limpiarCajasCliente();
        }
    }//GEN-LAST:event_btnCancelarEditarClienteActionPerformed

    private void txtDeudaEditarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeudaEditarClienteKeyTyped
        puntoFlotante(evt, txtDeudaEditarCliente);
    }//GEN-LAST:event_txtDeudaEditarClienteKeyTyped

    private void cmbDireccionEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDireccionEditarClienteActionPerformed

    }//GEN-LAST:event_cmbDireccionEditarClienteActionPerformed

    private void cmbDireccionEditarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDireccionEditarClienteMouseClicked

    }//GEN-LAST:event_cmbDireccionEditarClienteMouseClicked

    private void txtEditarTelefonoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarTelefonoProveedorKeyTyped
        Numeros(evt, 8, txtEditarTelefonoProveedor);
    }//GEN-LAST:event_txtEditarTelefonoProveedorKeyTyped

    private void txtEditarNombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarNombreProveedorKeyTyped
        Letras(evt);
    }//GEN-LAST:event_txtEditarNombreProveedorKeyTyped

    private void txtEditarApellidoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarApellidoProveedorKeyTyped
        Letras(evt);
    }//GEN-LAST:event_txtEditarApellidoProveedorKeyTyped

    private void cmbEditarDireccionProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEditarDireccionProveedorMouseClicked

    }//GEN-LAST:event_cmbEditarDireccionProveedorMouseClicked

    private void cmbEditarDireccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditarDireccionProveedorActionPerformed
    }//GEN-LAST:event_cmbEditarDireccionProveedorActionPerformed

    private void txtEditarDuedaProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditarDuedaProveedorKeyTyped
        puntoFlotante(evt, txtEditarDuedaProveedor);
    }//GEN-LAST:event_txtEditarDuedaProveedorKeyTyped

    private boolean verificarDatosProveedor() {
        if (txtEditarNombreProveedor.getText().length() == 0) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Campo Nombre vacío, por favor llénelo",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            txtEditarNombreProveedor.requestFocus();
            return false;
        } else if (txtEditarApellidoProveedor.getText().length() == 0) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Campo Apellido vacío, por favor llénelo",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            txtEditarApellidoProveedor.requestFocus();
            return false;
        } else if (txtEditarTelefonoProveedor.getText().length() == 0) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Campo Teléfono vacío, por favor llénelo",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            txtEditarTelefonoProveedor.requestFocus();
            return false;
        } else if (cmbEditarDireccionProveedor.getSelectedItem().equals("Escoja una opción")) {
            new rojerusan.RSNotifyAnimated("¡ERROR!", "Escoja un campo correcto en la dirección",
                    5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                    RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
            cmbEditarDireccionProveedor.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private void limpiarCajasProveedor() {
        txtEditarNombreProveedor.setText("");
        txtEditarApellidoProveedor.setText("");
        txtEditarTelefonoProveedor.setText("");
        txtEditarDuedaProveedor.setText("");
        txtEditarAreaDescripcionProveedor.setText("");
        cmbEditarDireccionProveedor.setSelectedIndex(0);
    }

    private void btnEditarGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGuardarProveedorActionPerformed
        if (verificarDatosProveedor()) {
            if (proveedor.ActualizarProveedor(Integer.parseInt(lblProveedorId.getText()), txtEditarNombreProveedor.getText(),
                    txtEditarApellidoProveedor.getText(), cmbEditarDireccionProveedor.getSelectedIndex(),
                    txtEditarAreaDescripcionProveedor.getText(), txtEditarTelefonoProveedor.getText(),
                    Float.parseFloat(txtEditarDuedaProveedor.getText()))) {
                new rojerusan.RSNotifyAnimated("¡ÉXITO!", "Proveedor editado correctamente",
                        5, RSNotifyAnimated.PositionNotify.BottomRight, RSNotifyAnimated.AnimationNotify.BottomUp,
                        RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                limpiarCajasProveedor();
                tblBusquedaProveedor.setModel(proveedor.buscarProveedores("", "", tblBusquedaProveedor));
                moverPanel(pnlBuscarProveedor, true, false, btnEditarGuardarProveedor, true);
            }
        }
    }//GEN-LAST:event_btnEditarGuardarProveedorActionPerformed

    private void btnEditarCancelarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCancelarProveedorActionPerformed

    }//GEN-LAST:event_btnEditarCancelarProveedorActionPerformed

    private void moverPanel(KGradientPanel panel, boolean mover, boolean no_mover, JButton boton, boolean opcion) {
        /*
            Si la variable opcion es verdadera quiere decir que la llamada a la función viene desde un botón, 
            si opcion es falsa quiere decir que la llamada a la función solo quiere mover un panel, y no viene
            desde ningún botón
         */
        if (opcion) {
            if (!boton.isSelected()) {
                boton.setSelected(mover);
                this.btnRegresarEditarCliente.setSelected(no_mover);
                this.btnRegresarBusquedaCliente.setSelected(no_mover);
                this.btnBusquedaCliente.setSelected(no_mover);
                this.btnBusquedaTapachula.setSelected(no_mover);
                this.btnProveedor.setSelected(no_mover);
                this.btnRegresarProveedor.setSelected(no_mover);
                this.btnRegresarProducto.setSelected(no_mover);
                this.btnGuardarEditarCliente.setSelected(no_mover);
                this.btnCancelarEditarCliente.setSelected(no_mover);
                this.btnRegresarEditarCliente.setSelected(no_mover);
                this.btnEditarCancelarProveedor.setSelected(no_mover);
                this.btnEditarGuardarProveedor.setSelected(no_mover);
                this.btnEditarRegresarProveedor.setSelected(no_mover);
                this.btnProveedor.setSelected(no_mover);
                this.btnRegresarProveedor.setSelected(no_mover);
                this.btnRegresarProducto.setSelected(no_mover);
                rSPanelsSlider1.setPanelSlider(10, panel, RSPanelsSlider.DIRECT.RIGHT);
            }
        } else {
            //Esto se usa para cuando el click vino de un JMenuItem y no desde un JButton
            this.btnRegresarEditarCliente.setSelected(no_mover);
            this.btnRegresarBusquedaCliente.setSelected(no_mover);
            this.btnBusquedaCliente.setSelected(no_mover);
            this.btnBusquedaTapachula.setSelected(no_mover);
            this.btnProveedor.setSelected(no_mover);
            this.btnRegresarProveedor.setSelected(no_mover);
            this.btnRegresarProducto.setSelected(no_mover);
            this.btnGuardarEditarCliente.setSelected(no_mover);
            this.btnCancelarEditarCliente.setSelected(no_mover);
            this.btnRegresarEditarCliente.setSelected(no_mover);
            this.btnEditarCancelarProveedor.setSelected(no_mover);
            this.btnEditarGuardarProveedor.setSelected(no_mover);
            this.btnEditarRegresarProveedor.setSelected(no_mover);
            this.btnProveedor.setSelected(no_mover);
            this.btnRegresarProveedor.setSelected(no_mover);
            this.btnRegresarProducto.setSelected(no_mover);
            this.btnRegresarDetalleTapachula.setSelected(no_mover);
            rSPanelsSlider1.setPanelSlider(10, panel, RSPanelsSlider.DIRECT.RIGHT);
        }

    }
    private void btnEditarRegresarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRegresarProveedorActionPerformed
        moverPanel(pnlBuscarProveedor, true, false, btnEditarRegresarProveedor, true);
    }//GEN-LAST:event_btnEditarRegresarProveedorActionPerformed

    private void ItemEditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarProveedorActionPerformed
        int seleccion = tblBusquedaProveedor.getSelectedRow();
        System.out.println(seleccion);
        String registros[] = new String[7];
        if (seleccion != -1) {
            int id = Integer.parseInt((String) tblBusquedaProveedor.getValueAt(seleccion, 0));
            System.out.println("seleccion: " + seleccion);
            moverPanel(pnlEditarProveedor, false, false, null, false);
            lblProveedorId.setText(String.valueOf(id));
            System.out.println("id: " + lblProveedorId.getText());
            registros = proveedor.getProveedor(id);
            txtEditarNombreProveedor.setText(registros[1]);
            txtEditarApellidoProveedor.setText(registros[2]);
            txtEditarAreaDescripcionProveedor.setText(registros[3]);
            txtEditarTelefonoProveedor.setText(registros[4]);
            cmbEditarDireccionProveedor.setSelectedItem(registros[5]);
            txtEditarDuedaProveedor.setText(registros[6]);
        }
    }//GEN-LAST:event_ItemEditarProveedorActionPerformed

    private void ItemEditarTapachulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarTapachulaActionPerformed
        int seleccion = tblBusquedaTapachula.getSelectedRow();
        System.out.println("seleccion: " + seleccion);
        if (seleccion != -1) {
            int id = Integer.parseInt((String) tblBusquedaTapachula.getValueAt(seleccion, 0));
            moverPanel(pnlDetalleTapachula, false, false, null, false);
            lblTapachulaId.setText(String.valueOf(id));
            System.out.println("id: " + id);
            tblDetalleViajeTapachula.setModel(tapachula.getDetalleTapachula(id, tblDetalleViajeTapachula));
        }
    }//GEN-LAST:event_ItemEditarTapachulaActionPerformed

    private void btnRegresarDetalleTapachulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDetalleTapachulaActionPerformed
        moverPanel(pnlBuscarTapachula, true, false, btnRegresarDetalleTapachula, true);
    }//GEN-LAST:event_btnRegresarDetalleTapachulaActionPerformed

    private final Cliente cliente;
    private final Proveedor proveedor;
    private final compra compra;
    private final viajes_tapachula tapachula;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemDetalleCliente;
    private javax.swing.JMenuItem ItemDetalleProveedor;
    private javax.swing.JMenuItem ItemEditarCliente;
    private javax.swing.JMenuItem ItemEditarProveedor;
    private javax.swing.JMenuItem ItemEditarTapachula;
    private javax.swing.JMenu MenuEditarCliente;
    private javax.swing.JMenu MenuEditarProveedor;
    private javax.swing.JMenu MenuEditarTapachula;
    private javax.swing.JPopupMenu PMEditarCliente;
    private javax.swing.JPopupMenu PMEditarProveedor;
    private javax.swing.JPopupMenu PMEditarTapachula;
    private javax.swing.JButton btnBusquedaCliente;
    private javax.swing.JButton btnBusquedaTapachula;
    private javax.swing.JButton btnCancelarEditarCliente;
    private javax.swing.JButton btnEditarCancelarProveedor;
    private javax.swing.JButton btnEditarGuardarProveedor;
    private javax.swing.JButton btnEditarRegresarProveedor;
    private javax.swing.JButton btnGuardarEditarCliente;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnRegresarBusquedaCliente;
    private javax.swing.JButton btnRegresarDetalleTapachula;
    private javax.swing.JButton btnRegresarEditarCliente;
    private javax.swing.JButton btnRegresarProducto;
    private javax.swing.JButton btnRegresarProveedor;
    private rojerusan.RSComboMetro cmbAnioTapachula;
    private rojerusan.RSComboMetro cmbBusquedaCliente;
    private rojerusan.RSComboMetro cmbBusquedaProveedor;
    private rojerusan.RSComboMetro cmbDireccionEditarCliente;
    private rojerusan.RSComboMetro cmbEditarDireccionProveedor;
    private rojerusan.RSComboMetro cmbMesTapachula;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblAnioTapachula;
    private javax.swing.JLabel lblApellidoEditarCliente;
    private javax.swing.JLabel lblApellidoProveedor;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblClienteId;
    private javax.swing.JLabel lblDescripcionProveedor;
    private javax.swing.JLabel lblDetalleViajeTapachula;
    private javax.swing.JLabel lblDeudaEditarCliente;
    private javax.swing.JLabel lblDeudaProveedor;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionBusquedaCliente;
    private javax.swing.JLabel lblDireccionBusquedaProveedor;
    private javax.swing.JLabel lblDireccionProveedor;
    private javax.swing.JLabel lblDisenio;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblMesTapachula;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblMover;
    private javax.swing.JLabel lblNombreBusquedaCliente;
    private javax.swing.JLabel lblNombreBusquedaProveedor;
    private javax.swing.JLabel lblNombreEditarCliente;
    private javax.swing.JLabel lblNombreProveedor;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblProveedorId;
    private javax.swing.JLabel lblTapachulaId;
    private javax.swing.JLabel lblTelefonoProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblViajeTapachula;
    private javax.swing.JLabel lblViajeTapachula1;
    private keeptoo.KGradientPanel pnlBuscarProveedor;
    private keeptoo.KGradientPanel pnlBuscarTapachula;
    private keeptoo.KGradientPanel pnlBusquedaCliente;
    private keeptoo.KGradientPanel pnlBusquedas;
    private keeptoo.KGradientPanel pnlDetalleTapachula;
    private keeptoo.KGradientPanel pnlEditarCliente;
    private keeptoo.KGradientPanel pnlEditarProveedor;
    private javax.swing.JPanel pnlOpciones;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSTableMetro tblBusquedaCliente;
    private rojerusan.RSTableMetro tblBusquedaProveedor;
    private rojerusan.RSTableMetro tblBusquedaTapachula;
    private rojerusan.RSTableMetro tblDetalleViajeTapachula;
    private javax.swing.JTextField txtApellidoEditarCliente;
    private javax.swing.JTextArea txtAreaDescripcionEditarCliente;
    private javax.swing.JTextField txtDeudaEditarCliente;
    private javax.swing.JTextField txtEditarApellidoProveedor;
    private javax.swing.JTextArea txtEditarAreaDescripcionProveedor;
    private javax.swing.JTextField txtEditarDuedaProveedor;
    private javax.swing.JTextField txtEditarNombreProveedor;
    private javax.swing.JTextField txtEditarTelefonoProveedor;
    private javax.swing.JTextField txtNombreBusquedaCliente;
    private javax.swing.JTextField txtNombreBusquedaProveedor;
    private javax.swing.JTextField txtNombreEditarCliente;
    private javax.swing.JTextField txtTelefonoEditarCliente;
    // End of variables declaration//GEN-END:variables
}
