/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import javax.swing.JOptionPane;
import rojerusan.RSPanelsSlider;
import Clases.Cliente;
import Clases.Proveedor;
import Clases.compra;
import Clases.viajes_tapachula;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import rojerusan.RSComboMetro;
/**
 *
 * @author hectortllo
 */
public class busquedas extends javax.swing.JFrame {

    /**
     * Creates new form Insertar
     */
    int x, y;
    public busquedas() {
        cliente = new Cliente();
        proveedor = new Proveedor();
        compra = new compra();
        tapachula = new viajes_tapachula();
        initComponents();
        cmbBusquedaCliente.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbBusquedaCliente.getModel()));
        cmbBusquedaProveedor.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbBusquedaProveedor.getModel()));
        cmbAnioTapachula.setModel(tapachula.getAnio((DefaultComboBoxModel) cmbAnioTapachula.getModel()));
        tblBusquedaCliente.setModel(cliente.buscarClientes("", "", tblBusquedaCliente));
        tblBusquedaProveedor.setModel(proveedor.buscarProveedores("", "", tblBusquedaProveedor));
        tblBusquedaTapachula.setModel(tapachula.buscarViajeTapachula((String)cmbAnioTapachula.getSelectedItem(), (String)cmbMesTapachula.getSelectedItem(), tblBusquedaTapachula));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisenio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMover = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        lblMenuPrincipal = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pnlBusquedas = new keeptoo.KGradientPanel();
        lblCliente = new javax.swing.JLabel();
        btnBusquedaCliente = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnBusquedaTapachula = new javax.swing.JButton();
        lblProveedor = new javax.swing.JLabel();
        lblViajeTapachula = new javax.swing.JLabel();
        lblViajeTapachula1 = new javax.swing.JLabel();
        pnlBusquedaCliente = new keeptoo.KGradientPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombreBusquedaCliente = new javax.swing.JLabel();
        lblDireccionBusquedaCliente = new javax.swing.JLabel();
        cmbBusquedaCliente = new rojerusan.RSComboMetro();
        txtNombreBusquedaCliente = new javax.swing.JTextField();
        btnRegresarBusquedaCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusquedaCliente = new rojerusan.RSTableMetro();
        pnlBuscarProveedor = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreBusquedaProveedor = new javax.swing.JLabel();
        lblDireccionBusquedaProveedor = new javax.swing.JLabel();
        txtNombreBusquedaProveedor = new javax.swing.JTextField();
        cmbBusquedaProveedor = new rojerusan.RSComboMetro();
        btnRegresarProveedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBusquedaProveedor = new rojerusan.RSTableMetro();
        pnlBuscarTapachula = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        lblMesTapachula = new javax.swing.JLabel();
        cmbAnioTapachula = new rojerusan.RSComboMetro();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBusquedaTapachula = new rojerusan.RSTableMetro();
        btnRegresarProducto = new javax.swing.JButton();
        lblAnioTapachula = new javax.swing.JLabel();
        cmbMesTapachula = new rojerusan.RSComboMetro();

        lblDisenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/lineas.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 30));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblMoverMouseDragged(evt);
            }
        });
        lblMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMoverMousePressed(evt);
            }
        });
        jPanel1.add(lblMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 30));

        pnlOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-página-principal-96.png"))); // NOI18N
        lblMenuPrincipal.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver al menú principal</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuPrincipalMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-eliminar-80.png"))); // NOI18N
        lblCerrar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cerrar aplicación</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 90, 80));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-chevron-abajo-en-círculo-95.png"))); // NOI18N
        lblMinimizar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Minimizar</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlOpciones.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 100, 100));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        pnlOpciones.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 110));

        jPanel1.add(pnlOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 110));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        pnlBusquedas.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBusquedas.setkGradientFocus(1000);
        pnlBusquedas.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBusquedas.setName("pnlBusquedas"); // NOI18N
        pnlBusquedas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(204, 204, 204));
        lblCliente.setText("CLIENTE");
        pnlBusquedas.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 190, 60));

        btnBusquedaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-usuario-masculino-240.png"))); // NOI18N
        btnBusquedaCliente.setContentAreaFilled(false);
        btnBusquedaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-proveedor-240.png"))); // NOI18N
        btnProveedor.setContentAreaFilled(false);
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        btnBusquedaTapachula.setForeground(new java.awt.Color(204, 204, 204));
        btnBusquedaTapachula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/tapachula.png"))); // NOI18N
        btnBusquedaTapachula.setContentAreaFilled(false);
        btnBusquedaTapachula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusquedaTapachula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaTapachulaActionPerformed(evt);
            }
        });
        pnlBusquedas.add(btnBusquedaTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, -1, -1));

        lblProveedor.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(204, 204, 204));
        lblProveedor.setText("PROVEEDOR");
        pnlBusquedas.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 260, 40));

        lblViajeTapachula.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblViajeTapachula.setForeground(new java.awt.Color(204, 204, 204));
        lblViajeTapachula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViajeTapachula.setText("VIAJES");
        lblViajeTapachula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBusquedas.add(lblViajeTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 250, 50));

        lblViajeTapachula1.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblViajeTapachula1.setForeground(new java.awt.Color(204, 204, 204));
        lblViajeTapachula1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViajeTapachula1.setText("TAPACHULA");
        lblViajeTapachula1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBusquedas.add(lblViajeTapachula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 250, 50));

        rSPanelsSlider1.add(pnlBusquedas, "card2");

        pnlBusquedaCliente.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBusquedaCliente.setkGradientFocus(1000);
        pnlBusquedaCliente.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBusquedaCliente.setName("pnlBusquedaCliente"); // NOI18N
        pnlBusquedaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 255, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("BÚSQUEDA POR CLIENTE");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlBusquedaCliente.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1170, 60));

        lblNombreBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblNombreBusquedaCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblNombreBusquedaCliente.setText("Nombre: ");
        pnlBusquedaCliente.add(lblNombreBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblDireccionBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblDireccionBusquedaCliente.setForeground(new java.awt.Color(204, 255, 153));
        lblDireccionBusquedaCliente.setText("Dirección:");
        pnlBusquedaCliente.add(lblDireccionBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        cmbBusquedaCliente.setForeground(new java.awt.Color(153, 102, 255));
        cmbBusquedaCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ver Todo" }));
        cmbBusquedaCliente.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbBusquedaCliente.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbBusquedaCliente.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbBusquedaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBusquedaClienteMouseClicked(evt);
            }
        });
        cmbBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedaCliente.add(cmbBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, 290, 40));

        txtNombreBusquedaCliente.setBackground(new java.awt.Color(204, 204, 255));
        txtNombreBusquedaCliente.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtNombreBusquedaCliente.setForeground(new java.awt.Color(153, 102, 255));
        txtNombreBusquedaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreBusquedaClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreBusquedaClienteKeyTyped(evt);
            }
        });
        pnlBusquedaCliente.add(txtNombreBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 240, 40));

        btnRegresarBusquedaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarBusquedaCliente.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarBusquedaCliente.setContentAreaFilled(false);
        btnRegresarBusquedaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarBusquedaClienteActionPerformed(evt);
            }
        });
        pnlBusquedaCliente.add(btnRegresarBusquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 80, 80));

        tblBusquedaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Apellido", "Teléfono", "Descripción", "Dirección", "Deuda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBusquedaCliente.setAltoHead(40);
        tblBusquedaCliente.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        tblBusquedaCliente.setFuenteFilas(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaCliente.setFuenteFilasSelect(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaCliente.setFuenteHead(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        tblBusquedaCliente.setRowHeight(25);
        jScrollPane1.setViewportView(tblBusquedaCliente);

        pnlBusquedaCliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 1090, 350));

        rSPanelsSlider1.add(pnlBusquedaCliente, "card3");

        pnlBuscarProveedor.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBuscarProveedor.setkGradientFocus(1000);
        pnlBuscarProveedor.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBuscarProveedor.setName("pnlBuscarProveedor"); // NOI18N
        pnlBuscarProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BÚSQUEDA POR PROVEEDOR");
        pnlBuscarProveedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 60));

        lblNombreBusquedaProveedor.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblNombreBusquedaProveedor.setForeground(new java.awt.Color(204, 255, 155));
        lblNombreBusquedaProveedor.setText("Nombre:");
        pnlBuscarProveedor.add(lblNombreBusquedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        lblDireccionBusquedaProveedor.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblDireccionBusquedaProveedor.setForeground(new java.awt.Color(204, 255, 153));
        lblDireccionBusquedaProveedor.setText("Dirección:");
        pnlBuscarProveedor.add(lblDireccionBusquedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        txtNombreBusquedaProveedor.setBackground(new java.awt.Color(204, 204, 255));
        txtNombreBusquedaProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        txtNombreBusquedaProveedor.setForeground(new java.awt.Color(153, 102, 255));
        txtNombreBusquedaProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreBusquedaProveedorKeyPressed(evt);
            }
        });
        pnlBuscarProveedor.add(txtNombreBusquedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 290, 40));

        cmbBusquedaProveedor.setForeground(new java.awt.Color(153, 102, 255));
        cmbBusquedaProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ver Todo" }));
        cmbBusquedaProveedor.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbBusquedaProveedor.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbBusquedaProveedor.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbBusquedaProveedor.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbBusquedaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBusquedaProveedorMouseClicked(evt);
            }
        });
        cmbBusquedaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBusquedaProveedorActionPerformed(evt);
            }
        });
        pnlBuscarProveedor.add(cmbBusquedaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 270, 40));

        btnRegresarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
        btnRegresarProveedor.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
        btnRegresarProveedor.setContentAreaFilled(false);
        btnRegresarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarProveedorActionPerformed(evt);
            }
        });
        pnlBuscarProveedor.add(btnRegresarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 110, 80));

        tblBusquedaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Apellido", "Teléfono", "Descripción", "Dirección", "Deuda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBusquedaProveedor.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        tblBusquedaProveedor.setFuenteFilas(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaProveedor.setFuenteFilasSelect(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        tblBusquedaProveedor.setFuenteHead(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        tblBusquedaProveedor.setRowHeight(25);
        jScrollPane2.setViewportView(tblBusquedaProveedor);

        pnlBuscarProveedor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1100, 390));

        rSPanelsSlider1.add(pnlBuscarProveedor, "card4");

        pnlBuscarTapachula.setkEndColor(new java.awt.Color(0, 51, 51));
        pnlBuscarTapachula.setkGradientFocus(1000);
        pnlBuscarTapachula.setkStartColor(new java.awt.Color(0, 204, 204));
        pnlBuscarTapachula.setName("pnlBuscarTapachula"); // NOI18N
        pnlBuscarTapachula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BÚSQUEDA VIAJE TAPACHULA");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBuscarTapachula.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 50));

        lblMesTapachula.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        lblMesTapachula.setForeground(new java.awt.Color(204, 255, 155));
        lblMesTapachula.setText("Mes:");
        pnlBuscarTapachula.add(lblMesTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        cmbAnioTapachula.setForeground(new java.awt.Color(153, 102, 255));
        cmbAnioTapachula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos los años", " " }));
        cmbAnioTapachula.setColorArrow(new java.awt.Color(255, 204, 204));
        cmbAnioTapachula.setColorBorde(new java.awt.Color(153, 153, 255));
        cmbAnioTapachula.setColorFondo(new java.awt.Color(204, 204, 255));
        cmbAnioTapachula.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        cmbAnioTapachula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbAnioTapachulaMouseClicked(evt);
            }
        });
        cmbAnioTapachula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAnioTapachulaActionPerformed(evt);
            }
        });
        pnlBuscarTapachula.add(cmbAnioTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 290, 40));

        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblBusquedaTapachula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblBusquedaTapachula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Fecha", "Lugares visitados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }
    );
    tblBusquedaTapachula.setAltoHead(40);
    tblBusquedaTapachula.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
    tblBusquedaTapachula.setFuenteFilas(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
    tblBusquedaTapachula.setFuenteFilasSelect(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
    tblBusquedaTapachula.setFuenteHead(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
    tblBusquedaTapachula.setRowHeight(25);
    jScrollPane4.setViewportView(tblBusquedaTapachula);

    pnlBuscarTapachula.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 1090, 390));

    btnRegresarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/regresar.png"))); // NOI18N
    btnRegresarProducto.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #0B6121;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Volver</h2>\n\t\t<!-- <img src=\"Path img\"> -->\n\t</div>\n</body>\n</html>");
    btnRegresarProducto.setContentAreaFilled(false);
    btnRegresarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRegresarProducto.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRegresarProductoActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(btnRegresarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 90, 80));

    lblAnioTapachula.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
    lblAnioTapachula.setForeground(new java.awt.Color(204, 255, 155));
    lblAnioTapachula.setText("Año:");
    pnlBuscarTapachula.add(lblAnioTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

    cmbMesTapachula.setForeground(new java.awt.Color(153, 102, 255));
    cmbMesTapachula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos los meses", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
    cmbMesTapachula.setColorArrow(new java.awt.Color(255, 204, 204));
    cmbMesTapachula.setColorBorde(new java.awt.Color(153, 153, 255));
    cmbMesTapachula.setColorFondo(new java.awt.Color(204, 204, 255));
    cmbMesTapachula.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
    cmbMesTapachula.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmbMesTapachulaActionPerformed(evt);
        }
    });
    pnlBuscarTapachula.add(cmbMesTapachula, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 290, 40));

    rSPanelsSlider1.add(pnlBuscarTapachula, "card5");

    jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1170, 550));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 660));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "CERRANDO", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lblMoverMouseDragged

    private void lblMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoverMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblMoverMousePressed

    private void btnBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaClienteActionPerformed
        if(!this.btnBusquedaCliente.isSelected())
        {
            rSPanelsSlider1.setPanelSlider(10, pnlBusquedaCliente, RSPanelsSlider.DIRECT.RIGHT);
            this.btnBusquedaCliente.setSelected(true);
            this.btnBusquedaTapachula.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnRegresarProducto.setSelected(false);
        }
    }//GEN-LAST:event_btnBusquedaClienteActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        if(!this.btnProveedor.isSelected())
        {
            this.btnProveedor.setSelected(true);
            this.btnBusquedaCliente.setSelected(false);
            this.btnBusquedaTapachula.setSelected(false);
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnRegresarProducto.setSelected(false);
            rSPanelsSlider1.setPanelSlider(10, pnlBuscarProveedor, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnBusquedaTapachulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaTapachulaActionPerformed
        if(!this.btnBusquedaTapachula.isSelected())
        {
            this.btnBusquedaTapachula.setSelected(true);
            this.btnBusquedaCliente.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            //agregarCamposAComboBox(cmbAnioTapachula, cmbBusquedaProveedor, 2);
            rSPanelsSlider1.setPanelSlider(10, pnlBuscarTapachula, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnBusquedaTapachulaActionPerformed

    private void lblMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuPrincipalMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "¿Volver al menú principal?", "MENÚ PRINCIPAL", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION)
        {
            this.dispose();
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
        }
            
    }//GEN-LAST:event_lblMenuPrincipalMouseClicked

    private void btnRegresarBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarBusquedaClienteActionPerformed
        if(!this.btnRegresarBusquedaCliente.isSelected())
        {
            this.btnRegresarBusquedaCliente.setSelected(true);
            this.btnBusquedaCliente.setSelected(false);
            this.btnBusquedaTapachula.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnRegresarProducto.setSelected(false);
            rSPanelsSlider1.setPanelSlider(10, pnlBusquedas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnRegresarBusquedaClienteActionPerformed

    
    private void btnRegresarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarProveedorActionPerformed
        if(!this.btnRegresarProveedor.isSelected())
        {
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnBusquedaCliente.setSelected(false);
            this.btnBusquedaTapachula.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(true);
            this.btnRegresarProducto.setSelected(false);
            rSPanelsSlider1.setPanelSlider(10, pnlBusquedas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnRegresarProveedorActionPerformed

    private void cmbBusquedaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBusquedaClienteMouseClicked
    }//GEN-LAST:event_cmbBusquedaClienteMouseClicked

    private void cmbBusquedaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBusquedaProveedorMouseClicked
    }//GEN-LAST:event_cmbBusquedaProveedorMouseClicked

    private void cmbBusquedaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBusquedaProveedorActionPerformed
        BusquedaProveedor();
    }//GEN-LAST:event_cmbBusquedaProveedorActionPerformed

    private void Numeros(KeyEvent e) {
        if ((e.getKeyChar() < '0' || e.getKeyChar() > '9')) {                           //Si no es un numero se va a consumir 
            e.consume();
        }
    }
    
    private void agregarCamposAComboBox(RSComboMetro cmbDireccionCliente, RSComboMetro cmbDireccionProveedor, int opcion)
    {
        for (int i = cmbDireccionCliente.getItemCount() - 1; i > 0; i--) {
                cmbDireccionCliente.removeItemAt(i);
        }
        for (int i = cmbDireccionProveedor.getItemCount() - 1; i > 0; i--) {
                cmbDireccionProveedor.removeItemAt(i);
        }
        //cmbDireccion.removeAllItems();
        //cmbDireccion.addItem("Escoja una opción");
        cmbDireccionCliente.addItem("Agregar");
        cmbDireccionProveedor.addItem("Agregar");
        switch(opcion)
        {    
            case 1:
                String direccion = JOptionPane.showInputDialog("Ingrese la nueva dirección: ");
                if(direccion != null)
                {
                    /*Actualizar los cmb del cliente y del proveedor. Entrará en este caso si la dirección
                        ingresada fue desde el cmb de cliente
                    */
                    proveedor.insertarDireccion(direccion);
                    cmbDireccionCliente.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbDireccionCliente.getModel()));
                    cmbDireccionProveedor.setModel(cliente.getDireccion((DefaultComboBoxModel) cmbDireccionProveedor.getModel()));
                }
                break;
                
            case 2:
                cmbDireccionCliente.setModel(proveedor.getProveedor((DefaultComboBoxModel) cmbDireccionCliente.getModel()));
                break;
        }
    }
    
    private void BusquedaCliente() {
        //Declaro variables a utilizar. Y les asigno valores con if ternarios si dicen ver todo les mando cadena vacía si no lo que este en el combobox.
        String direccion; 
        direccion = cmbBusquedaCliente.getSelectedItem().equals("Ver Todo") ? "" : (String) cmbBusquedaCliente.getSelectedItem();
        tblBusquedaCliente.setModel(cliente.buscarClientes(txtNombreBusquedaCliente.getText(), direccion, tblBusquedaCliente));
    }
    
    private void BusquedaProveedor() {
        //Declaro variables a utilizar. Y les asigno valores con if ternarios si dicen ver todo les mando cadena vacía si no lo que este en el combobox.
        String direccion; 
        direccion = cmbBusquedaProveedor.getSelectedItem().equals("Ver Todo") ? "" : (String) cmbBusquedaProveedor.getSelectedItem();
        tblBusquedaProveedor.setModel(proveedor.buscarProveedores(txtNombreBusquedaProveedor.getText(), direccion, tblBusquedaProveedor));
    }
    
    private void BusquedaTapachula(){
        String anio, mes;
        anio = cmbAnioTapachula.getSelectedItem().equals("Todos los años") ? "Todos los años" : (String)cmbAnioTapachula.getSelectedItem();
        mes = cmbMesTapachula.getSelectedItem().equals("Todos los meses") ? "Todos los meses" : String.valueOf(cmbMesTapachula.getSelectedIndex());
        tblBusquedaTapachula.setModel(tapachula.buscarViajeTapachula(anio, mes, tblBusquedaTapachula));
    }
    private void cmbBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBusquedaClienteActionPerformed
        BusquedaCliente();      
    }//GEN-LAST:event_cmbBusquedaClienteActionPerformed

    private void btnRegresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarProductoActionPerformed
        if(!this.btnRegresarProducto.isSelected())
        {
            this.btnRegresarBusquedaCliente.setSelected(false);
            this.btnBusquedaCliente.setSelected(false);
            this.btnBusquedaTapachula.setSelected(false);
            this.btnProveedor.setSelected(false);
            this.btnRegresarProveedor.setSelected(false);
            this.btnRegresarProducto.setSelected(true);
            rSPanelsSlider1.setPanelSlider(10, pnlBusquedas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnRegresarProductoActionPerformed

    private void cmbAnioTapachulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnioTapachulaActionPerformed
        BusquedaTapachula();
    }//GEN-LAST:event_cmbAnioTapachulaActionPerformed

    private void cmbAnioTapachulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbAnioTapachulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAnioTapachulaMouseClicked

    private void cmbMesTapachulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesTapachulaActionPerformed
        BusquedaTapachula();
    }//GEN-LAST:event_cmbMesTapachulaActionPerformed

    private void txtNombreBusquedaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBusquedaClienteKeyPressed
        BusquedaCliente();
    }//GEN-LAST:event_txtNombreBusquedaClienteKeyPressed

    private void txtNombreBusquedaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBusquedaClienteKeyTyped

    }//GEN-LAST:event_txtNombreBusquedaClienteKeyTyped

    private void txtNombreBusquedaProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBusquedaProveedorKeyPressed
        BusquedaProveedor();
    }//GEN-LAST:event_txtNombreBusquedaProveedorKeyPressed

           
    private final Cliente cliente;
    private final Proveedor proveedor;
    private final compra compra;
    private final viajes_tapachula tapachula;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaCliente;
    private javax.swing.JButton btnBusquedaTapachula;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnRegresarBusquedaCliente;
    private javax.swing.JButton btnRegresarProducto;
    private javax.swing.JButton btnRegresarProveedor;
    private rojerusan.RSComboMetro cmbAnioTapachula;
    private rojerusan.RSComboMetro cmbBusquedaCliente;
    private rojerusan.RSComboMetro cmbBusquedaProveedor;
    private rojerusan.RSComboMetro cmbMesTapachula;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblAnioTapachula;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDireccionBusquedaCliente;
    private javax.swing.JLabel lblDireccionBusquedaProveedor;
    private javax.swing.JLabel lblDisenio;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblMesTapachula;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblMover;
    private javax.swing.JLabel lblNombreBusquedaCliente;
    private javax.swing.JLabel lblNombreBusquedaProveedor;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblViajeTapachula;
    private javax.swing.JLabel lblViajeTapachula1;
    private keeptoo.KGradientPanel pnlBuscarProveedor;
    private keeptoo.KGradientPanel pnlBuscarTapachula;
    private keeptoo.KGradientPanel pnlBusquedaCliente;
    private keeptoo.KGradientPanel pnlBusquedas;
    private javax.swing.JPanel pnlOpciones;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private rojerusan.RSTableMetro tblBusquedaCliente;
    private rojerusan.RSTableMetro tblBusquedaProveedor;
    private rojerusan.RSTableMetro tblBusquedaTapachula;
    private javax.swing.JTextField txtNombreBusquedaCliente;
    private javax.swing.JTextField txtNombreBusquedaProveedor;
    // End of variables declaration//GEN-END:variables
}
